'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace OnlineService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EntidadVinculada_BE", [Namespace]:="http://schemas.datacontract.org/2004/07/Application.BusinessEntities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EntidadVinculada_BE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecCreaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecModField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrCreaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrModField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoTipoVigenciaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoTipoVinculacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorreoContactoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_CodigoVinculadaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_DocIdenVinculadaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreContactoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VigenciaDesdeField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VigenciaHastaField As System.Nullable(Of Date)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecCrea() As Date
            Get
                Return Me.AUDI_FecCreaField
            End Get
            Set
                If (Me.AUDI_FecCreaField.Equals(value) <> true) Then
                    Me.AUDI_FecCreaField = value
                    Me.RaisePropertyChanged("AUDI_FecCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecMod() As Date
            Get
                Return Me.AUDI_FecModField
            End Get
            Set
                If (Me.AUDI_FecModField.Equals(value) <> true) Then
                    Me.AUDI_FecModField = value
                    Me.RaisePropertyChanged("AUDI_FecMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrCrea() As String
            Get
                Return Me.AUDI_UsrCreaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrCreaField, value) <> true) Then
                    Me.AUDI_UsrCreaField = value
                    Me.RaisePropertyChanged("AUDI_UsrCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrMod() As String
            Get
                Return Me.AUDI_UsrModField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrModField, value) <> true) Then
                    Me.AUDI_UsrModField = value
                    Me.RaisePropertyChanged("AUDI_UsrMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoTipoVigencia() As String
            Get
                Return Me.CodigoTipoVigenciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoTipoVigenciaField, value) <> true) Then
                    Me.CodigoTipoVigenciaField = value
                    Me.RaisePropertyChanged("CodigoTipoVigencia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoTipoVinculacion() As String
            Get
                Return Me.CodigoTipoVinculacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoTipoVinculacionField, value) <> true) Then
                    Me.CodigoTipoVinculacionField = value
                    Me.RaisePropertyChanged("CodigoTipoVinculacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorreoContacto() As String
            Get
                Return Me.CorreoContactoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorreoContactoField, value) <> true) Then
                    Me.CorreoContactoField = value
                    Me.RaisePropertyChanged("CorreoContacto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_Codigo() As Integer
            Get
                Return Me.ENTC_CodigoField
            End Get
            Set
                If (Me.ENTC_CodigoField.Equals(value) <> true) Then
                    Me.ENTC_CodigoField = value
                    Me.RaisePropertyChanged("ENTC_Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_CodigoVinculada() As Integer
            Get
                Return Me.ENTC_CodigoVinculadaField
            End Get
            Set
                If (Me.ENTC_CodigoVinculadaField.Equals(value) <> true) Then
                    Me.ENTC_CodigoVinculadaField = value
                    Me.RaisePropertyChanged("ENTC_CodigoVinculada")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_DocIdenVinculada() As String
            Get
                Return Me.ENTC_DocIdenVinculadaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ENTC_DocIdenVinculadaField, value) <> true) Then
                    Me.ENTC_DocIdenVinculadaField = value
                    Me.RaisePropertyChanged("ENTC_DocIdenVinculada")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Estado() As String
            Get
                Return Me.EstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoField, value) <> true) Then
                    Me.EstadoField = value
                    Me.RaisePropertyChanged("Estado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreContacto() As String
            Get
                Return Me.NombreContactoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreContactoField, value) <> true) Then
                    Me.NombreContactoField = value
                    Me.RaisePropertyChanged("NombreContacto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VigenciaDesde() As System.Nullable(Of Date)
            Get
                Return Me.VigenciaDesdeField
            End Get
            Set
                If (Me.VigenciaDesdeField.Equals(value) <> true) Then
                    Me.VigenciaDesdeField = value
                    Me.RaisePropertyChanged("VigenciaDesde")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VigenciaHasta() As System.Nullable(Of Date)
            Get
                Return Me.VigenciaHastaField
            End Get
            Set
                If (Me.VigenciaHastaField.Equals(value) <> true) Then
                    Me.VigenciaHastaField = value
                    Me.RaisePropertyChanged("VigenciaHasta")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EntidadRegistro_BE", [Namespace]:="http://schemas.datacontract.org/2004/07/Application.BusinessEntities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EntidadRegistro_BE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecCreaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecModField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrCreaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrModField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_DocIdenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_EMailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_EmailReceptorFEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_OrigenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_RazonSocialField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_Telef1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private REGI_CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private REGI_EstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TIPO_CodTDIField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecCrea() As Date
            Get
                Return Me.AUDI_FecCreaField
            End Get
            Set
                If (Me.AUDI_FecCreaField.Equals(value) <> true) Then
                    Me.AUDI_FecCreaField = value
                    Me.RaisePropertyChanged("AUDI_FecCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecMod() As Date
            Get
                Return Me.AUDI_FecModField
            End Get
            Set
                If (Me.AUDI_FecModField.Equals(value) <> true) Then
                    Me.AUDI_FecModField = value
                    Me.RaisePropertyChanged("AUDI_FecMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrCrea() As String
            Get
                Return Me.AUDI_UsrCreaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrCreaField, value) <> true) Then
                    Me.AUDI_UsrCreaField = value
                    Me.RaisePropertyChanged("AUDI_UsrCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrMod() As String
            Get
                Return Me.AUDI_UsrModField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrModField, value) <> true) Then
                    Me.AUDI_UsrModField = value
                    Me.RaisePropertyChanged("AUDI_UsrMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_Codigo() As Integer
            Get
                Return Me.ENTC_CodigoField
            End Get
            Set
                If (Me.ENTC_CodigoField.Equals(value) <> true) Then
                    Me.ENTC_CodigoField = value
                    Me.RaisePropertyChanged("ENTC_Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_DocIden() As String
            Get
                Return Me.ENTC_DocIdenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ENTC_DocIdenField, value) <> true) Then
                    Me.ENTC_DocIdenField = value
                    Me.RaisePropertyChanged("ENTC_DocIden")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_EMail() As String
            Get
                Return Me.ENTC_EMailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ENTC_EMailField, value) <> true) Then
                    Me.ENTC_EMailField = value
                    Me.RaisePropertyChanged("ENTC_EMail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_EmailReceptorFE() As String
            Get
                Return Me.ENTC_EmailReceptorFEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ENTC_EmailReceptorFEField, value) <> true) Then
                    Me.ENTC_EmailReceptorFEField = value
                    Me.RaisePropertyChanged("ENTC_EmailReceptorFE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_Origen() As String
            Get
                Return Me.ENTC_OrigenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ENTC_OrigenField, value) <> true) Then
                    Me.ENTC_OrigenField = value
                    Me.RaisePropertyChanged("ENTC_Origen")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_RazonSocial() As String
            Get
                Return Me.ENTC_RazonSocialField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ENTC_RazonSocialField, value) <> true) Then
                    Me.ENTC_RazonSocialField = value
                    Me.RaisePropertyChanged("ENTC_RazonSocial")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_Telef1() As String
            Get
                Return Me.ENTC_Telef1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ENTC_Telef1Field, value) <> true) Then
                    Me.ENTC_Telef1Field = value
                    Me.RaisePropertyChanged("ENTC_Telef1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property REGI_Codigo() As Integer
            Get
                Return Me.REGI_CodigoField
            End Get
            Set
                If (Me.REGI_CodigoField.Equals(value) <> true) Then
                    Me.REGI_CodigoField = value
                    Me.RaisePropertyChanged("REGI_Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property REGI_Estado() As String
            Get
                Return Me.REGI_EstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.REGI_EstadoField, value) <> true) Then
                    Me.REGI_EstadoField = value
                    Me.RaisePropertyChanged("REGI_Estado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TIPO_CodTDI() As String
            Get
                Return Me.TIPO_CodTDIField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TIPO_CodTDIField, value) <> true) Then
                    Me.TIPO_CodTDIField = value
                    Me.RaisePropertyChanged("TIPO_CodTDI")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EntidadDireccionamiento_BE", [Namespace]:="http://schemas.datacontract.org/2004/07/Application.BusinessEntities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EntidadDireccionamiento_BE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecCreaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecModField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrCreaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrModField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoRespuestaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DOOV_HBLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescargaDirectaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionEstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionRespuestaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENDI_EstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENDI_NumeroField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_CodDepTemporalField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_CodDepTemporalSolicitadoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_EMailSolicitanteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EsAnulableField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaMaxDireccionamientoField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreClienteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreDepositoTemporalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreDepositoTemporalAsignadoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecCrea() As Date
            Get
                Return Me.AUDI_FecCreaField
            End Get
            Set
                If (Me.AUDI_FecCreaField.Equals(value) <> true) Then
                    Me.AUDI_FecCreaField = value
                    Me.RaisePropertyChanged("AUDI_FecCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecMod() As System.Nullable(Of Date)
            Get
                Return Me.AUDI_FecModField
            End Get
            Set
                If (Me.AUDI_FecModField.Equals(value) <> true) Then
                    Me.AUDI_FecModField = value
                    Me.RaisePropertyChanged("AUDI_FecMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrCrea() As String
            Get
                Return Me.AUDI_UsrCreaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrCreaField, value) <> true) Then
                    Me.AUDI_UsrCreaField = value
                    Me.RaisePropertyChanged("AUDI_UsrCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrMod() As String
            Get
                Return Me.AUDI_UsrModField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrModField, value) <> true) Then
                    Me.AUDI_UsrModField = value
                    Me.RaisePropertyChanged("AUDI_UsrMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoRespuesta() As String
            Get
                Return Me.CodigoRespuestaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoRespuestaField, value) <> true) Then
                    Me.CodigoRespuestaField = value
                    Me.RaisePropertyChanged("CodigoRespuesta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DOOV_HBL() As String
            Get
                Return Me.DOOV_HBLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DOOV_HBLField, value) <> true) Then
                    Me.DOOV_HBLField = value
                    Me.RaisePropertyChanged("DOOV_HBL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DescargaDirecta() As Boolean
            Get
                Return Me.DescargaDirectaField
            End Get
            Set
                If (Me.DescargaDirectaField.Equals(value) <> true) Then
                    Me.DescargaDirectaField = value
                    Me.RaisePropertyChanged("DescargaDirecta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DescripcionEstado() As String
            Get
                Return Me.DescripcionEstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionEstadoField, value) <> true) Then
                    Me.DescripcionEstadoField = value
                    Me.RaisePropertyChanged("DescripcionEstado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DescripcionRespuesta() As String
            Get
                Return Me.DescripcionRespuestaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionRespuestaField, value) <> true) Then
                    Me.DescripcionRespuestaField = value
                    Me.RaisePropertyChanged("DescripcionRespuesta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENDI_Estado() As String
            Get
                Return Me.ENDI_EstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ENDI_EstadoField, value) <> true) Then
                    Me.ENDI_EstadoField = value
                    Me.RaisePropertyChanged("ENDI_Estado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENDI_Numero() As Integer
            Get
                Return Me.ENDI_NumeroField
            End Get
            Set
                If (Me.ENDI_NumeroField.Equals(value) <> true) Then
                    Me.ENDI_NumeroField = value
                    Me.RaisePropertyChanged("ENDI_Numero")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_CodDepTemporal() As Integer
            Get
                Return Me.ENTC_CodDepTemporalField
            End Get
            Set
                If (Me.ENTC_CodDepTemporalField.Equals(value) <> true) Then
                    Me.ENTC_CodDepTemporalField = value
                    Me.RaisePropertyChanged("ENTC_CodDepTemporal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_CodDepTemporalSolicitado() As Integer
            Get
                Return Me.ENTC_CodDepTemporalSolicitadoField
            End Get
            Set
                If (Me.ENTC_CodDepTemporalSolicitadoField.Equals(value) <> true) Then
                    Me.ENTC_CodDepTemporalSolicitadoField = value
                    Me.RaisePropertyChanged("ENTC_CodDepTemporalSolicitado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_Codigo() As Integer
            Get
                Return Me.ENTC_CodigoField
            End Get
            Set
                If (Me.ENTC_CodigoField.Equals(value) <> true) Then
                    Me.ENTC_CodigoField = value
                    Me.RaisePropertyChanged("ENTC_Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_EMailSolicitante() As String
            Get
                Return Me.ENTC_EMailSolicitanteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ENTC_EMailSolicitanteField, value) <> true) Then
                    Me.ENTC_EMailSolicitanteField = value
                    Me.RaisePropertyChanged("ENTC_EMailSolicitante")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EsAnulable() As Boolean
            Get
                Return Me.EsAnulableField
            End Get
            Set
                If (Me.EsAnulableField.Equals(value) <> true) Then
                    Me.EsAnulableField = value
                    Me.RaisePropertyChanged("EsAnulable")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaMaxDireccionamiento() As System.Nullable(Of Date)
            Get
                Return Me.FechaMaxDireccionamientoField
            End Get
            Set
                If (Me.FechaMaxDireccionamientoField.Equals(value) <> true) Then
                    Me.FechaMaxDireccionamientoField = value
                    Me.RaisePropertyChanged("FechaMaxDireccionamiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreCliente() As String
            Get
                Return Me.NombreClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreClienteField, value) <> true) Then
                    Me.NombreClienteField = value
                    Me.RaisePropertyChanged("NombreCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreDepositoTemporal() As String
            Get
                Return Me.NombreDepositoTemporalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreDepositoTemporalField, value) <> true) Then
                    Me.NombreDepositoTemporalField = value
                    Me.RaisePropertyChanged("NombreDepositoTemporal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreDepositoTemporalAsignado() As String
            Get
                Return Me.NombreDepositoTemporalAsignadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreDepositoTemporalAsignadoField, value) <> true) Then
                    Me.NombreDepositoTemporalAsignadoField = value
                    Me.RaisePropertyChanged("NombreDepositoTemporalAsignado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="VoyageQueryDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class VoyageQueryDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoNaveField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ETA_ETDField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaCierreDireccionamientoField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreNaveField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PuertoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TerminalPortuarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TransportistaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Viaje_VueloField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoNave() As String
            Get
                Return Me.CodigoNaveField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoNaveField, value) <> true) Then
                    Me.CodigoNaveField = value
                    Me.RaisePropertyChanged("CodigoNave")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ETA_ETD() As System.Nullable(Of Date)
            Get
                Return Me.ETA_ETDField
            End Get
            Set
                If (Me.ETA_ETDField.Equals(value) <> true) Then
                    Me.ETA_ETDField = value
                    Me.RaisePropertyChanged("ETA_ETD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaCierreDireccionamiento() As System.Nullable(Of Date)
            Get
                Return Me.FechaCierreDireccionamientoField
            End Get
            Set
                If (Me.FechaCierreDireccionamientoField.Equals(value) <> true) Then
                    Me.FechaCierreDireccionamientoField = value
                    Me.RaisePropertyChanged("FechaCierreDireccionamiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreNave() As String
            Get
                Return Me.NombreNaveField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreNaveField, value) <> true) Then
                    Me.NombreNaveField = value
                    Me.RaisePropertyChanged("NombreNave")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Puerto() As String
            Get
                Return Me.PuertoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PuertoField, value) <> true) Then
                    Me.PuertoField = value
                    Me.RaisePropertyChanged("Puerto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TerminalPortuario() As String
            Get
                Return Me.TerminalPortuarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TerminalPortuarioField, value) <> true) Then
                    Me.TerminalPortuarioField = value
                    Me.RaisePropertyChanged("TerminalPortuario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Transportista() As String
            Get
                Return Me.TransportistaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TransportistaField, value) <> true) Then
                    Me.TransportistaField = value
                    Me.RaisePropertyChanged("Transportista")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Viaje_Vuelo() As String
            Get
                Return Me.Viaje_VueloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Viaje_VueloField, value) <> true) Then
                    Me.Viaje_VueloField = value
                    Me.RaisePropertyChanged("Viaje_Vuelo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="OnlineService.IOnLineService")>  _
    Public Interface IOnLineService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetData", ReplyAction:="http://tempuri.org/IOnLineService/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetData", ReplyAction:="http://tempuri.org/IOnLineService/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IOnLineService/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As OnlineService.CompositeType) As OnlineService.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IOnLineService/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As OnlineService.CompositeType) As System.Threading.Tasks.Task(Of OnlineService.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/ExecuteSQL", ReplyAction:="http://tempuri.org/IOnLineService/ExecuteSQLResponse")>  _
        Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/ExecuteSQL", ReplyAction:="http://tempuri.org/IOnLineService/ExecuteSQLResponse")>  _
        Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IOnLineService/ExecuteSQLNonQueryResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.EntidadVinculada_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.EntidadRegistro_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.EntidadDireccionamiento_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.EntidadDireccionamiento_BE())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.CompositeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.VoyageQueryDTO())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.VoyageQueryDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function ExecuteSQLNonQuery(ByVal QueryString As String) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IOnLineService/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/VoyageQuery", ReplyAction:="http://tempuri.org/IOnLineService/VoyageQueryResponse")>  _
        Function VoyageQuery(ByVal Days As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/VoyageQuery", ReplyAction:="http://tempuri.org/IOnLineService/VoyageQueryResponse")>  _
        Function VoyageQueryAsync(ByVal Days As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/VoyageQueryList", ReplyAction:="http://tempuri.org/IOnLineService/VoyageQueryListResponse")>  _
        Function VoyageQueryList() As OnlineService.VoyageQueryDTO()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/VoyageQueryList", ReplyAction:="http://tempuri.org/IOnLineService/VoyageQueryListResponse")>  _
        Function VoyageQueryListAsync() As System.Threading.Tasks.Task(Of OnlineService.VoyageQueryDTO())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/InvoicingQuery", ReplyAction:="http://tempuri.org/IOnLineService/InvoicingQueryResponse")>  _
        Function InvoicingQuery(ByVal CustomerCode As Integer, ByVal DateFrom As Date, ByVal DateTo As Date) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/InvoicingQuery", ReplyAction:="http://tempuri.org/IOnLineService/InvoicingQueryResponse")>  _
        Function InvoicingQueryAsync(ByVal CustomerCode As Integer, ByVal DateFrom As Date, ByVal DateTo As Date) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/CargoNoticeQuery", ReplyAction:="http://tempuri.org/IOnLineService/CargoNoticeQueryResponse")>  _
        Function CargoNoticeQuery(ByVal HouseBL As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/CargoNoticeQuery", ReplyAction:="http://tempuri.org/IOnLineService/CargoNoticeQueryResponse")>  _
        Function CargoNoticeQueryAsync(ByVal HouseBL As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetVoyageByCustomer", ReplyAction:="http://tempuri.org/IOnLineService/GetVoyageByCustomerResponse")>  _
        Function GetVoyageByCustomer(ByVal CustomerCode As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetVoyageByCustomer", ReplyAction:="http://tempuri.org/IOnLineService/GetVoyageByCustomerResponse")>  _
        Function GetVoyageByCustomerAsync(ByVal CustomerCode As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/CargoAddressingQuery", ReplyAction:="http://tempuri.org/IOnLineService/CargoAddressingQueryResponse")>  _
        Function CargoAddressingQuery(ByVal CustomerCode As Integer, ByVal Voyage As Integer, ByVal HouseBL As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/CargoAddressingQuery", ReplyAction:="http://tempuri.org/IOnLineService/CargoAddressingQueryResponse")>  _
        Function CargoAddressingQueryAsync(ByVal CustomerCode As Integer, ByVal Voyage As Integer, ByVal HouseBL As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/CustomerDocumentQuery", ReplyAction:="http://tempuri.org/IOnLineService/CustomerDocumentQueryResponse")>  _
        Function CustomerDocumentQuery(ByVal DocumentType As String, ByVal DocumentNUmber As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/CustomerDocumentQuery", ReplyAction:="http://tempuri.org/IOnLineService/CustomerDocumentQueryResponse")>  _
        Function CustomerDocumentQueryAsync(ByVal DocumentType As String, ByVal DocumentNUmber As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/CustomerDebtQuery", ReplyAction:="http://tempuri.org/IOnLineService/CustomerDebtQueryResponse")>  _
        Function CustomerDebtQuery(ByVal CustomerCode As Integer, ByVal HouseBL As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/CustomerDebtQuery", ReplyAction:="http://tempuri.org/IOnLineService/CustomerDebtQueryResponse")>  _
        Function CustomerDebtQueryAsync(ByVal CustomerCode As Integer, ByVal HouseBL As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/HBLStatusQuery", ReplyAction:="http://tempuri.org/IOnLineService/HBLStatusQueryResponse")>  _
        Function HBLStatusQuery(ByVal HouseBL As String, ByVal CustomerCode As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/HBLStatusQuery", ReplyAction:="http://tempuri.org/IOnLineService/HBLStatusQueryResponse")>  _
        Function HBLStatusQueryAsync(ByVal HouseBL As String, ByVal CustomerCode As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/RelatedCompanyQuery", ReplyAction:="http://tempuri.org/IOnLineService/RelatedCompanyQueryResponse")>  _
        Function RelatedCompanyQuery(ByVal CompanyCode As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/RelatedCompanyQuery", ReplyAction:="http://tempuri.org/IOnLineService/RelatedCompanyQueryResponse")>  _
        Function RelatedCompanyQueryAsync(ByVal CompanyCode As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/InsertRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/InsertRelatedCompanyResponse")>  _
        Sub InsertRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/InsertRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/InsertRelatedCompanyResponse")>  _
        Function InsertRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/UpdateRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/UpdateRelatedCompanyResponse")>  _
        Sub UpdateRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/UpdateRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/UpdateRelatedCompanyResponse")>  _
        Function UpdateRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/StatusUpdateRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/StatusUpdateRelatedCompanyResponse")>  _
        Sub StatusUpdateRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/StatusUpdateRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/StatusUpdateRelatedCompanyResponse")>  _
        Function StatusUpdateRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/DeleteRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/DeleteRelatedCompanyResponse")>  _
        Sub DeleteRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/DeleteRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/DeleteRelatedCompanyResponse")>  _
        Function DeleteRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetAllRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/GetAllRelatedCompanyResponse")>  _
        Function GetAllRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As OnlineService.EntidadVinculada_BE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetAllRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/GetAllRelatedCompanyResponse")>  _
        Function GetAllRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task(Of OnlineService.EntidadVinculada_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetAllDataTableRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/GetAllDataTableRelatedCompanyResponse")>  _
        Function GetAllDataTableRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetAllDataTableRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/GetAllDataTableRelatedCompanyResponse")>  _
        Function GetAllDataTableRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetDataList", ReplyAction:="http://tempuri.org/IOnLineService/GetDataListResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.EntidadVinculada_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.EntidadRegistro_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.EntidadDireccionamiento_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.EntidadDireccionamiento_BE())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.CompositeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.VoyageQueryDTO())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OnlineService.VoyageQueryDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function GetDataList(ByVal TableName As String, ByVal Params() As Object) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetDataList", ReplyAction:="http://tempuri.org/IOnLineService/GetDataListResponse")>  _
        Function GetDataListAsync(ByVal TableName As String, ByVal Params() As Object) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/GetRelatedCompanyResponse")>  _
        Function GetRelatedCompany(ByVal DocumentNumber As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetRelatedCompany", ReplyAction:="http://tempuri.org/IOnLineService/GetRelatedCompanyResponse")>  _
        Function GetRelatedCompanyAsync(ByVal DocumentNumber As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetDataByEntityType", ReplyAction:="http://tempuri.org/IOnLineService/GetDataByEntityTypeResponse")>  _
        Function GetDataByEntityType(ByVal EntityType As Integer, ByVal DocumentNumber As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetDataByEntityType", ReplyAction:="http://tempuri.org/IOnLineService/GetDataByEntityTypeResponse")>  _
        Function GetDataByEntityTypeAsync(ByVal EntityType As Integer, ByVal DocumentNumber As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/InsertCustomerRegister", ReplyAction:="http://tempuri.org/IOnLineService/InsertCustomerRegisterResponse")>  _
        Sub InsertCustomerRegister(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/InsertCustomerRegister", ReplyAction:="http://tempuri.org/IOnLineService/InsertCustomerRegisterResponse")>  _
        Function InsertCustomerRegisterAsync(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/StatusUpdateCustomerRegister", ReplyAction:="http://tempuri.org/IOnLineService/StatusUpdateCustomerRegisterResponse")>  _
        Sub StatusUpdateCustomerRegister(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/StatusUpdateCustomerRegister", ReplyAction:="http://tempuri.org/IOnLineService/StatusUpdateCustomerRegisterResponse")>  _
        Function StatusUpdateCustomerRegisterAsync(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetAllDataTableCustomerRegister", ReplyAction:="http://tempuri.org/IOnLineService/GetAllDataTableCustomerRegisterResponse")>  _
        Function GetAllDataTableCustomerRegister(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetAllDataTableCustomerRegister", ReplyAction:="http://tempuri.org/IOnLineService/GetAllDataTableCustomerRegisterResponse")>  _
        Function GetAllDataTableCustomerRegisterAsync(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/OperationalTracking", ReplyAction:="http://tempuri.org/IOnLineService/OperationalTrackingResponse")>  _
        Function OperationalTracking(ByVal CustomerCode As Integer, ByVal HouseBL As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/OperationalTracking", ReplyAction:="http://tempuri.org/IOnLineService/OperationalTrackingResponse")>  _
        Function OperationalTrackingAsync(ByVal CustomerCode As Integer, ByVal HouseBL As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/CustomerStatementQuery", ReplyAction:="http://tempuri.org/IOnLineService/CustomerStatementQueryResponse")>  _
        Function CustomerStatementQuery(ByVal CustomerCode As Integer, ByVal DateFrom As Date, ByVal DateTo As Date, ByVal QueryType As String, ByVal HouseBL As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/CustomerStatementQuery", ReplyAction:="http://tempuri.org/IOnLineService/CustomerStatementQueryResponse")>  _
        Function CustomerStatementQueryAsync(ByVal CustomerCode As Integer, ByVal DateFrom As Date, ByVal DateTo As Date, ByVal QueryType As String, ByVal HouseBL As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/InsertEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/InsertEntidadDireccionamientoResponse")>  _
        Function InsertEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As OnlineService.EntidadDireccionamiento_BE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/InsertEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/InsertEntidadDireccionamientoResponse")>  _
        Function InsertEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task(Of OnlineService.EntidadDireccionamiento_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/UpdateEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/UpdateEntidadDireccionamientoResponse")>  _
        Sub UpdateEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/UpdateEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/UpdateEntidadDireccionamientoResponse")>  _
        Function UpdateEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/DeleteEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/DeleteEntidadDireccionamientoResponse")>  _
        Sub DeleteEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/DeleteEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/DeleteEntidadDireccionamientoResponse")>  _
        Function DeleteEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/ValidarDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/ValidarDireccionamientoResponse")>  _
        Function ValidarDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As OnlineService.EntidadDireccionamiento_BE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/ValidarDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/ValidarDireccionamientoResponse")>  _
        Function ValidarDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task(Of OnlineService.EntidadDireccionamiento_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetByFilterEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/GetByFilterEntidadDireccionamientoResponse")>  _
        Function GetByFilterEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As OnlineService.EntidadDireccionamiento_BE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetByFilterEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/GetByFilterEntidadDireccionamientoResponse")>  _
        Function GetByFilterEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task(Of OnlineService.EntidadDireccionamiento_BE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetAllDataTableEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/GetAllDataTableEntidadDireccionamientoResponse")>  _
        Function GetAllDataTableEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetAllDataTableEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/GetAllDataTableEntidadDireccionamientoResponse")>  _
        Function GetAllDataTableEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetAllEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/GetAllEntidadDireccionamientoResponse")>  _
        Function GetAllEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As OnlineService.EntidadDireccionamiento_BE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOnLineService/GetAllEntidadDireccionamiento", ReplyAction:="http://tempuri.org/IOnLineService/GetAllEntidadDireccionamientoResponse")>  _
        Function GetAllEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task(Of OnlineService.EntidadDireccionamiento_BE)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IOnLineServiceChannel
        Inherits OnlineService.IOnLineService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OnLineServiceClient
        Inherits System.ServiceModel.ClientBase(Of OnlineService.IOnLineService)
        Implements OnlineService.IOnLineService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements OnlineService.IOnLineService.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements OnlineService.IOnLineService.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As OnlineService.CompositeType) As OnlineService.CompositeType Implements OnlineService.IOnLineService.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As OnlineService.CompositeType) As System.Threading.Tasks.Task(Of OnlineService.CompositeType) Implements OnlineService.IOnLineService.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
        
        Public Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements OnlineService.IOnLineService.ExecuteSQL
            Return MyBase.Channel.ExecuteSQL(QueryString)
        End Function
        
        Public Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements OnlineService.IOnLineService.ExecuteSQLAsync
            Return MyBase.Channel.ExecuteSQLAsync(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQuery(ByVal QueryString As String) As Object() Implements OnlineService.IOnLineService.ExecuteSQLNonQuery
            Return MyBase.Channel.ExecuteSQLNonQuery(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object()) Implements OnlineService.IOnLineService.ExecuteSQLNonQueryAsync
            Return MyBase.Channel.ExecuteSQLNonQueryAsync(QueryString)
        End Function
        
        Public Function VoyageQuery(ByVal Days As Integer) As System.Data.DataTable Implements OnlineService.IOnLineService.VoyageQuery
            Return MyBase.Channel.VoyageQuery(Days)
        End Function
        
        Public Function VoyageQueryAsync(ByVal Days As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.VoyageQueryAsync
            Return MyBase.Channel.VoyageQueryAsync(Days)
        End Function
        
        Public Function VoyageQueryList() As OnlineService.VoyageQueryDTO() Implements OnlineService.IOnLineService.VoyageQueryList
            Return MyBase.Channel.VoyageQueryList
        End Function
        
        Public Function VoyageQueryListAsync() As System.Threading.Tasks.Task(Of OnlineService.VoyageQueryDTO()) Implements OnlineService.IOnLineService.VoyageQueryListAsync
            Return MyBase.Channel.VoyageQueryListAsync
        End Function
        
        Public Function InvoicingQuery(ByVal CustomerCode As Integer, ByVal DateFrom As Date, ByVal DateTo As Date) As System.Data.DataTable Implements OnlineService.IOnLineService.InvoicingQuery
            Return MyBase.Channel.InvoicingQuery(CustomerCode, DateFrom, DateTo)
        End Function
        
        Public Function InvoicingQueryAsync(ByVal CustomerCode As Integer, ByVal DateFrom As Date, ByVal DateTo As Date) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.InvoicingQueryAsync
            Return MyBase.Channel.InvoicingQueryAsync(CustomerCode, DateFrom, DateTo)
        End Function
        
        Public Function CargoNoticeQuery(ByVal HouseBL As String) As System.Data.DataSet Implements OnlineService.IOnLineService.CargoNoticeQuery
            Return MyBase.Channel.CargoNoticeQuery(HouseBL)
        End Function
        
        Public Function CargoNoticeQueryAsync(ByVal HouseBL As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements OnlineService.IOnLineService.CargoNoticeQueryAsync
            Return MyBase.Channel.CargoNoticeQueryAsync(HouseBL)
        End Function
        
        Public Function GetVoyageByCustomer(ByVal CustomerCode As Integer) As System.Data.DataTable Implements OnlineService.IOnLineService.GetVoyageByCustomer
            Return MyBase.Channel.GetVoyageByCustomer(CustomerCode)
        End Function
        
        Public Function GetVoyageByCustomerAsync(ByVal CustomerCode As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.GetVoyageByCustomerAsync
            Return MyBase.Channel.GetVoyageByCustomerAsync(CustomerCode)
        End Function
        
        Public Function CargoAddressingQuery(ByVal CustomerCode As Integer, ByVal Voyage As Integer, ByVal HouseBL As String) As System.Data.DataTable Implements OnlineService.IOnLineService.CargoAddressingQuery
            Return MyBase.Channel.CargoAddressingQuery(CustomerCode, Voyage, HouseBL)
        End Function
        
        Public Function CargoAddressingQueryAsync(ByVal CustomerCode As Integer, ByVal Voyage As Integer, ByVal HouseBL As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.CargoAddressingQueryAsync
            Return MyBase.Channel.CargoAddressingQueryAsync(CustomerCode, Voyage, HouseBL)
        End Function
        
        Public Function CustomerDocumentQuery(ByVal DocumentType As String, ByVal DocumentNUmber As String) As System.Data.DataTable Implements OnlineService.IOnLineService.CustomerDocumentQuery
            Return MyBase.Channel.CustomerDocumentQuery(DocumentType, DocumentNUmber)
        End Function
        
        Public Function CustomerDocumentQueryAsync(ByVal DocumentType As String, ByVal DocumentNUmber As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.CustomerDocumentQueryAsync
            Return MyBase.Channel.CustomerDocumentQueryAsync(DocumentType, DocumentNUmber)
        End Function
        
        Public Function CustomerDebtQuery(ByVal CustomerCode As Integer, ByVal HouseBL As String) As System.Data.DataTable Implements OnlineService.IOnLineService.CustomerDebtQuery
            Return MyBase.Channel.CustomerDebtQuery(CustomerCode, HouseBL)
        End Function
        
        Public Function CustomerDebtQueryAsync(ByVal CustomerCode As Integer, ByVal HouseBL As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.CustomerDebtQueryAsync
            Return MyBase.Channel.CustomerDebtQueryAsync(CustomerCode, HouseBL)
        End Function
        
        Public Function HBLStatusQuery(ByVal HouseBL As String, ByVal CustomerCode As Integer) As System.Data.DataTable Implements OnlineService.IOnLineService.HBLStatusQuery
            Return MyBase.Channel.HBLStatusQuery(HouseBL, CustomerCode)
        End Function
        
        Public Function HBLStatusQueryAsync(ByVal HouseBL As String, ByVal CustomerCode As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.HBLStatusQueryAsync
            Return MyBase.Channel.HBLStatusQueryAsync(HouseBL, CustomerCode)
        End Function
        
        Public Function RelatedCompanyQuery(ByVal CompanyCode As Integer) As System.Data.DataTable Implements OnlineService.IOnLineService.RelatedCompanyQuery
            Return MyBase.Channel.RelatedCompanyQuery(CompanyCode)
        End Function
        
        Public Function RelatedCompanyQueryAsync(ByVal CompanyCode As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.RelatedCompanyQueryAsync
            Return MyBase.Channel.RelatedCompanyQueryAsync(CompanyCode)
        End Function
        
        Public Sub InsertRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) Implements OnlineService.IOnLineService.InsertRelatedCompany
            MyBase.Channel.InsertRelatedCompany(oRelatedCompany)
        End Sub
        
        Public Function InsertRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task Implements OnlineService.IOnLineService.InsertRelatedCompanyAsync
            Return MyBase.Channel.InsertRelatedCompanyAsync(oRelatedCompany)
        End Function
        
        Public Sub UpdateRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) Implements OnlineService.IOnLineService.UpdateRelatedCompany
            MyBase.Channel.UpdateRelatedCompany(oRelatedCompany)
        End Sub
        
        Public Function UpdateRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task Implements OnlineService.IOnLineService.UpdateRelatedCompanyAsync
            Return MyBase.Channel.UpdateRelatedCompanyAsync(oRelatedCompany)
        End Function
        
        Public Sub StatusUpdateRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) Implements OnlineService.IOnLineService.StatusUpdateRelatedCompany
            MyBase.Channel.StatusUpdateRelatedCompany(oRelatedCompany)
        End Sub
        
        Public Function StatusUpdateRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task Implements OnlineService.IOnLineService.StatusUpdateRelatedCompanyAsync
            Return MyBase.Channel.StatusUpdateRelatedCompanyAsync(oRelatedCompany)
        End Function
        
        Public Sub DeleteRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) Implements OnlineService.IOnLineService.DeleteRelatedCompany
            MyBase.Channel.DeleteRelatedCompany(oRelatedCompany)
        End Sub
        
        Public Function DeleteRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task Implements OnlineService.IOnLineService.DeleteRelatedCompanyAsync
            Return MyBase.Channel.DeleteRelatedCompanyAsync(oRelatedCompany)
        End Function
        
        Public Function GetAllRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As OnlineService.EntidadVinculada_BE Implements OnlineService.IOnLineService.GetAllRelatedCompany
            Return MyBase.Channel.GetAllRelatedCompany(oRelatedCompany)
        End Function
        
        Public Function GetAllRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task(Of OnlineService.EntidadVinculada_BE) Implements OnlineService.IOnLineService.GetAllRelatedCompanyAsync
            Return MyBase.Channel.GetAllRelatedCompanyAsync(oRelatedCompany)
        End Function
        
        Public Function GetAllDataTableRelatedCompany(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Data.DataTable Implements OnlineService.IOnLineService.GetAllDataTableRelatedCompany
            Return MyBase.Channel.GetAllDataTableRelatedCompany(oRelatedCompany)
        End Function
        
        Public Function GetAllDataTableRelatedCompanyAsync(ByVal oRelatedCompany As OnlineService.EntidadVinculada_BE) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.GetAllDataTableRelatedCompanyAsync
            Return MyBase.Channel.GetAllDataTableRelatedCompanyAsync(oRelatedCompany)
        End Function
        
        Public Function GetDataList(ByVal TableName As String, ByVal Params() As Object) As System.Data.DataTable Implements OnlineService.IOnLineService.GetDataList
            Return MyBase.Channel.GetDataList(TableName, Params)
        End Function
        
        Public Function GetDataListAsync(ByVal TableName As String, ByVal Params() As Object) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.GetDataListAsync
            Return MyBase.Channel.GetDataListAsync(TableName, Params)
        End Function
        
        Public Function GetRelatedCompany(ByVal DocumentNumber As String) As System.Data.DataTable Implements OnlineService.IOnLineService.GetRelatedCompany
            Return MyBase.Channel.GetRelatedCompany(DocumentNumber)
        End Function
        
        Public Function GetRelatedCompanyAsync(ByVal DocumentNumber As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.GetRelatedCompanyAsync
            Return MyBase.Channel.GetRelatedCompanyAsync(DocumentNumber)
        End Function
        
        Public Function GetDataByEntityType(ByVal EntityType As Integer, ByVal DocumentNumber As String) As System.Data.DataSet Implements OnlineService.IOnLineService.GetDataByEntityType
            Return MyBase.Channel.GetDataByEntityType(EntityType, DocumentNumber)
        End Function
        
        Public Function GetDataByEntityTypeAsync(ByVal EntityType As Integer, ByVal DocumentNumber As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements OnlineService.IOnLineService.GetDataByEntityTypeAsync
            Return MyBase.Channel.GetDataByEntityTypeAsync(EntityType, DocumentNumber)
        End Function
        
        Public Sub InsertCustomerRegister(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE) Implements OnlineService.IOnLineService.InsertCustomerRegister
            MyBase.Channel.InsertCustomerRegister(oCustomerRegister)
        End Sub
        
        Public Function InsertCustomerRegisterAsync(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE) As System.Threading.Tasks.Task Implements OnlineService.IOnLineService.InsertCustomerRegisterAsync
            Return MyBase.Channel.InsertCustomerRegisterAsync(oCustomerRegister)
        End Function
        
        Public Sub StatusUpdateCustomerRegister(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE) Implements OnlineService.IOnLineService.StatusUpdateCustomerRegister
            MyBase.Channel.StatusUpdateCustomerRegister(oCustomerRegister)
        End Sub
        
        Public Function StatusUpdateCustomerRegisterAsync(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE) As System.Threading.Tasks.Task Implements OnlineService.IOnLineService.StatusUpdateCustomerRegisterAsync
            Return MyBase.Channel.StatusUpdateCustomerRegisterAsync(oCustomerRegister)
        End Function
        
        Public Function GetAllDataTableCustomerRegister(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE) As System.Data.DataTable Implements OnlineService.IOnLineService.GetAllDataTableCustomerRegister
            Return MyBase.Channel.GetAllDataTableCustomerRegister(oCustomerRegister)
        End Function
        
        Public Function GetAllDataTableCustomerRegisterAsync(ByVal oCustomerRegister As OnlineService.EntidadRegistro_BE) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.GetAllDataTableCustomerRegisterAsync
            Return MyBase.Channel.GetAllDataTableCustomerRegisterAsync(oCustomerRegister)
        End Function
        
        Public Function OperationalTracking(ByVal CustomerCode As Integer, ByVal HouseBL As String) As System.Data.DataSet Implements OnlineService.IOnLineService.OperationalTracking
            Return MyBase.Channel.OperationalTracking(CustomerCode, HouseBL)
        End Function
        
        Public Function OperationalTrackingAsync(ByVal CustomerCode As Integer, ByVal HouseBL As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements OnlineService.IOnLineService.OperationalTrackingAsync
            Return MyBase.Channel.OperationalTrackingAsync(CustomerCode, HouseBL)
        End Function
        
        Public Function CustomerStatementQuery(ByVal CustomerCode As Integer, ByVal DateFrom As Date, ByVal DateTo As Date, ByVal QueryType As String, ByVal HouseBL As String) As System.Data.DataTable Implements OnlineService.IOnLineService.CustomerStatementQuery
            Return MyBase.Channel.CustomerStatementQuery(CustomerCode, DateFrom, DateTo, QueryType, HouseBL)
        End Function
        
        Public Function CustomerStatementQueryAsync(ByVal CustomerCode As Integer, ByVal DateFrom As Date, ByVal DateTo As Date, ByVal QueryType As String, ByVal HouseBL As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.CustomerStatementQueryAsync
            Return MyBase.Channel.CustomerStatementQueryAsync(CustomerCode, DateFrom, DateTo, QueryType, HouseBL)
        End Function
        
        Public Function InsertEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As OnlineService.EntidadDireccionamiento_BE Implements OnlineService.IOnLineService.InsertEntidadDireccionamiento
            Return MyBase.Channel.InsertEntidadDireccionamiento(oEntidadDireccionamiento)
        End Function
        
        Public Function InsertEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task(Of OnlineService.EntidadDireccionamiento_BE) Implements OnlineService.IOnLineService.InsertEntidadDireccionamientoAsync
            Return MyBase.Channel.InsertEntidadDireccionamientoAsync(oEntidadDireccionamiento)
        End Function
        
        Public Sub UpdateEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) Implements OnlineService.IOnLineService.UpdateEntidadDireccionamiento
            MyBase.Channel.UpdateEntidadDireccionamiento(oEntidadDireccionamiento)
        End Sub
        
        Public Function UpdateEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task Implements OnlineService.IOnLineService.UpdateEntidadDireccionamientoAsync
            Return MyBase.Channel.UpdateEntidadDireccionamientoAsync(oEntidadDireccionamiento)
        End Function
        
        Public Sub DeleteEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) Implements OnlineService.IOnLineService.DeleteEntidadDireccionamiento
            MyBase.Channel.DeleteEntidadDireccionamiento(oEntidadDireccionamiento)
        End Sub
        
        Public Function DeleteEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task Implements OnlineService.IOnLineService.DeleteEntidadDireccionamientoAsync
            Return MyBase.Channel.DeleteEntidadDireccionamientoAsync(oEntidadDireccionamiento)
        End Function
        
        Public Function ValidarDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As OnlineService.EntidadDireccionamiento_BE Implements OnlineService.IOnLineService.ValidarDireccionamiento
            Return MyBase.Channel.ValidarDireccionamiento(oEntidadDireccionamiento)
        End Function
        
        Public Function ValidarDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task(Of OnlineService.EntidadDireccionamiento_BE) Implements OnlineService.IOnLineService.ValidarDireccionamientoAsync
            Return MyBase.Channel.ValidarDireccionamientoAsync(oEntidadDireccionamiento)
        End Function
        
        Public Function GetByFilterEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As OnlineService.EntidadDireccionamiento_BE() Implements OnlineService.IOnLineService.GetByFilterEntidadDireccionamiento
            Return MyBase.Channel.GetByFilterEntidadDireccionamiento(oEntidadDireccionamiento)
        End Function
        
        Public Function GetByFilterEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task(Of OnlineService.EntidadDireccionamiento_BE()) Implements OnlineService.IOnLineService.GetByFilterEntidadDireccionamientoAsync
            Return MyBase.Channel.GetByFilterEntidadDireccionamientoAsync(oEntidadDireccionamiento)
        End Function
        
        Public Function GetAllDataTableEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Data.DataTable Implements OnlineService.IOnLineService.GetAllDataTableEntidadDireccionamiento
            Return MyBase.Channel.GetAllDataTableEntidadDireccionamiento(oEntidadDireccionamiento)
        End Function
        
        Public Function GetAllDataTableEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements OnlineService.IOnLineService.GetAllDataTableEntidadDireccionamientoAsync
            Return MyBase.Channel.GetAllDataTableEntidadDireccionamientoAsync(oEntidadDireccionamiento)
        End Function
        
        Public Function GetAllEntidadDireccionamiento(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As OnlineService.EntidadDireccionamiento_BE Implements OnlineService.IOnLineService.GetAllEntidadDireccionamiento
            Return MyBase.Channel.GetAllEntidadDireccionamiento(oEntidadDireccionamiento)
        End Function
        
        Public Function GetAllEntidadDireccionamientoAsync(ByVal oEntidadDireccionamiento As OnlineService.EntidadDireccionamiento_BE) As System.Threading.Tasks.Task(Of OnlineService.EntidadDireccionamiento_BE) Implements OnlineService.IOnLineService.GetAllEntidadDireccionamientoAsync
            Return MyBase.Channel.GetAllEntidadDireccionamientoAsync(oEntidadDireccionamiento)
        End Function
    End Class
End Namespace
