'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BusinessUnit
    Public Property IdBusinessUnit As Integer
    Public Property BusinessUnitCode As String
    Public Property BusinessUnitDescription As String
    Public Property IdCompany As Integer
    Public Property UserCreate As String
    Public Property DateCreate As Nullable(Of Date)
    Public Property UserUpdate As String
    Public Property DateUpdate As Nullable(Of Date)
    Public Property BusinessUnitStatus As String
    Public Property EquivalentCode As String

End Class
