'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COM_Servicio
    Public Property SERV_Codigo As Integer
    Public Property SERV_Nombre_SPA As String
    Public Property SERV_Nombre_ENG As String
    Public Property SERV_AfeIgv As Nullable(Of Boolean)
    Public Property SERV_Flete As Nullable(Of Boolean)
    Public Property SERV_AfeDet As Nullable(Of Boolean)
    Public Property CONS_TabVia As String
    Public Property CONS_CodVia As String
    Public Property SERV_Activo As Boolean
    Public Property SERV_CueVta As String
    Public Property SERV_CueGas As String
    Public Property SERV_Agrup1 As String
    Public Property SERV_Agrup2 As String
    Public Property SERV_PorDet As Decimal
    Public Property SERV_Tipo As String
    Public Property SERV_Valor As Decimal
    Public Property SERV_CobMin As Decimal
    Public Property SERV_Autom As Nullable(Of Boolean)
    Public Property SERV_FrecFac As String
    Public Property TIPO_TabUNT As String
    Public Property TIPO_CodUNT As String
    Public Property AUDI_UsrCrea As String
    Public Property AUDI_FecCrea As Date
    Public Property AUDI_UsrMod As String
    Public Property AUDI_FecMod As String
    Public Property CONS_TabRGM As String
    Public Property CONS_CodRGM As String
    Public Property SERV_CuenIngreso As String
    Public Property SERV_CuenCosto As String
    Public Property SERV_CuenPuente As String
    Public Property TIPO_TabDET As String
    Public Property TIPO_CodDET As String
    Public Property SERV_NombreCorto As String
    Public Property SERV_Glosa As String
    Public Property SERV_Observaciones As String
    Public Property SERV_TipoMov As String
    Public Property CONS_TabBAS As String
    Public Property CONS_CodBAS As String
    Public Property TIPO_TabMND As String
    Public Property TIPO_CodMND As String
    Public Property CONS_TabLNG As String
    Public Property CONS_CodLNG As String
    Public Property SERV_DefinidoPor As String
    Public Property SERV_ExcesoFlete As Boolean
    Public Property CENT_Ano As String
    Public Property CENT_Codigo As String
    Public Property TIPO_TabOPE As String
    Public Property TIPO_CodOPE As String
    Public Property TIPO_TabOPE_Costo As String
    Public Property TIPO_CodOPE_Costo As String
    Public Property SERV_Agrupado As Nullable(Of Boolean)

    Public Overridable Property Tipos As Tipos
    Public Overridable Property Tipos1 As Tipos
    Public Overridable Property Constantes As Constantes
    Public Overridable Property Constantes1 As Constantes
    Public Overridable Property Constantes2 As Constantes
    Public Overridable Property Constantes3 As Constantes

End Class
