'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Concept
    Public Property IdConcept As Integer
    Public Property ConceptCode As String
    Public Property ConceptDescription As String
    Public Property ConceptShortDescription As String
    Public Property ConceptSource As String
    Public Property ConceptStatus As String
    Public Property UserCreate As String
    Public Property DateCreate As Nullable(Of Date)
    Public Property UserUpdate As String
    Public Property DateUpdate As Nullable(Of Date)
    Public Property EquivalentCode As Nullable(Of Integer)

End Class
