'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Constantes
    Public Property CONS_CodTabla As String
    Public Property CONS_CodTipo As String
    Public Property CONS_Desc_SPA As String
    Public Property CONS_Desc_ENG As String

End Class
