'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Layout
    Public Property IdLayout As Integer
    Public Property LayoutCode As String
    Public Property LayoutDescription As String
    Public Property IdConcept As Nullable(Of Integer)
    Public Property IdPack As Nullable(Of Integer)
    Public Property IdCondition As Nullable(Of Short)
    Public Property LayoutStatus As String
    Public Property UserCreate As String
    Public Property DateCreate As Nullable(Of Date)
    Public Property UserUpdate As String
    Public Property DateUpdate As Nullable(Of Date)
    Public Property IdBusinessUnit As Nullable(Of Integer)

    Public Overridable Property LayoutAttribute As ICollection(Of LayoutAttribute) = New HashSet(Of LayoutAttribute)

End Class
