'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PackConcept
    Public Property IdPackConcept As Integer
    Public Property IdPack As Integer
    Public Property IdConcept As Integer
    Public Property UserCreate As String
    Public Property DateCreate As Nullable(Of Date)
    Public Property UserUpdate As String
    Public Property DateUpdate As Nullable(Of Date)

    Public Overridable Property Concept As Concept

End Class
