'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class TarifarioEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TarifarioEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Attribute() As DbSet(Of Attribute)
    Public Overridable Property BusinessUnit() As DbSet(Of BusinessUnit)
    Public Overridable Property Condition() As DbSet(Of Condition)
    Public Overridable Property Layout() As DbSet(Of Layout)
    Public Overridable Property LayoutAttribute() As DbSet(Of LayoutAttribute)
    Public Overridable Property TariffDetail() As DbSet(Of TariffDetail)
    Public Overridable Property Unit() As DbSet(Of Unit)
    Public Overridable Property Company() As DbSet(Of Company)
    Public Overridable Property Group() As DbSet(Of Group)
    Public Overridable Property Concept() As DbSet(Of Concept)
    Public Overridable Property Tariff() As DbSet(Of Tariff)
    Public Overridable Property Pack() As DbSet(Of Pack)
    Public Overridable Property PackDetail() As DbSet(Of PackDetail)

    Public Overridable Function uspValueAttributes(idAttribute As Nullable(Of Integer)) As ObjectResult(Of uspValueAttributes_Result)
        Dim idAttributeParameter As ObjectParameter = If(idAttribute.HasValue, New ObjectParameter("IdAttribute", idAttribute), New ObjectParameter("IdAttribute", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of uspValueAttributes_Result)("uspValueAttributes", idAttributeParameter)
    End Function

    Public Overridable Function upGetAttributeDescription(idAttribute As Nullable(Of Integer), value As String) As ObjectResult(Of String)
        Dim idAttributeParameter As ObjectParameter = If(idAttribute.HasValue, New ObjectParameter("idAttribute", idAttribute), New ObjectParameter("idAttribute", GetType(Integer)))

        Dim valueParameter As ObjectParameter = If(value IsNot Nothing, New ObjectParameter("value", value), New ObjectParameter("value", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("upGetAttributeDescription", idAttributeParameter, valueParameter)
    End Function

End Class
