'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TariffDetail
    Public Property IdTariffDetail As Integer
    Public Property IdTariff As Integer
    Public Property IdConcept As Integer
    Public Property IdUnit As Short
    Public Property Currency As String
    Public Property SalesAmount As Nullable(Of Decimal)
    Public Property CostsAmount As Nullable(Of Decimal)
    Public Property ContributionMargin As Nullable(Of Decimal)
    Public Property UserCreate As String
    Public Property DateCreate As Nullable(Of Date)
    Public Property UserUpdate As String
    Public Property DateUpdate As Nullable(Of Date)

End Class
