//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delfin.Principal.IntegrationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntegrationService.IIntegradorSBO")]
    public interface IIntegradorSBO {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarServicio", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarServicioResponse")]
        ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarServicio(System.Data.DataSet dsServicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarServicio", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarServicioResponse")]
        System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarServicioAsync(System.Data.DataSet dsServicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarSocioNegocio", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarSocioNegocioResponse")]
        ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarSocioNegocio(System.Data.DataSet dsCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarSocioNegocio", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarSocioNegocioResponse")]
        System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarSocioNegocioAsync(System.Data.DataSet dsCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarReferencias", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarReferenciasResponse")]
        ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarReferencias(System.Data.DataSet dsReferencias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarReferencias", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarReferenciasResponse")]
        System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarReferenciasAsync(System.Data.DataSet dsReferencias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarJournalEntry", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarJournalEntryResponse")]
        ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarJournalEntry(System.Data.DataSet dsJournalEntry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarJournalEntry", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarJournalEntryResponse")]
        System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarJournalEntryAsync(System.Data.DataSet dsJournalEntry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarInvoiceBills", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarInvoiceBillsResponse")]
        ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarInvoiceBills(System.Data.DataSet dsInvoiceBills);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarInvoiceBills", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarInvoiceBillsResponse")]
        System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarInvoiceBillsAsync(System.Data.DataSet dsInvoiceBills);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarCreditMemo", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarCreditMemoResponse")]
        ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarCreditMemo(System.Data.DataSet dsCreditMemo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarCreditMemo", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarCreditMemoResponse")]
        System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarCreditMemoAsync(System.Data.DataSet dsCreditMemo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarPurchaseInvoice", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarPurchaseInvoiceResponse")]
        ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarPurchaseInvoice(System.Data.DataSet dsPurchaseInvoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarPurchaseInvoice", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarPurchaseInvoiceResponse")]
        System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarPurchaseInvoiceAsync(System.Data.DataSet dsPurchaseInvoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarPurchaseCreditMemo", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarPurchaseCreditMemoResponse")]
        ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarPurchaseCreditMemo(System.Data.DataSet PurchaseCreditMemo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSBO/InsertarActualizarPurchaseCreditMemo", ReplyAction="http://tempuri.org/IIntegradorSBO/InsertarActualizarPurchaseCreditMemoResponse")]
        System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarPurchaseCreditMemoAsync(System.Data.DataSet PurchaseCreditMemo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegradorSBOChannel : Delfin.Principal.IntegrationService.IIntegradorSBO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegradorSBOClient : System.ServiceModel.ClientBase<Delfin.Principal.IntegrationService.IIntegradorSBO>, Delfin.Principal.IntegrationService.IIntegradorSBO {
        
        public IntegradorSBOClient() {
        }
        
        public IntegradorSBOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegradorSBOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegradorSBOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegradorSBOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarServicio(System.Data.DataSet dsServicio) {
            return base.Channel.InsertarActualizarServicio(dsServicio);
        }
        
        public System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarServicioAsync(System.Data.DataSet dsServicio) {
            return base.Channel.InsertarActualizarServicioAsync(dsServicio);
        }
        
        public ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarSocioNegocio(System.Data.DataSet dsCliente) {
            return base.Channel.InsertarActualizarSocioNegocio(dsCliente);
        }
        
        public System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarSocioNegocioAsync(System.Data.DataSet dsCliente) {
            return base.Channel.InsertarActualizarSocioNegocioAsync(dsCliente);
        }
        
        public ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarReferencias(System.Data.DataSet dsReferencias) {
            return base.Channel.InsertarActualizarReferencias(dsReferencias);
        }
        
        public System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarReferenciasAsync(System.Data.DataSet dsReferencias) {
            return base.Channel.InsertarActualizarReferenciasAsync(dsReferencias);
        }
        
        public ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarJournalEntry(System.Data.DataSet dsJournalEntry) {
            return base.Channel.InsertarActualizarJournalEntry(dsJournalEntry);
        }
        
        public System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarJournalEntryAsync(System.Data.DataSet dsJournalEntry) {
            return base.Channel.InsertarActualizarJournalEntryAsync(dsJournalEntry);
        }
        
        public ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarInvoiceBills(System.Data.DataSet dsInvoiceBills) {
            return base.Channel.InsertarActualizarInvoiceBills(dsInvoiceBills);
        }
        
        public System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarInvoiceBillsAsync(System.Data.DataSet dsInvoiceBills) {
            return base.Channel.InsertarActualizarInvoiceBillsAsync(dsInvoiceBills);
        }
        
        public ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarCreditMemo(System.Data.DataSet dsCreditMemo) {
            return base.Channel.InsertarActualizarCreditMemo(dsCreditMemo);
        }
        
        public System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarCreditMemoAsync(System.Data.DataSet dsCreditMemo) {
            return base.Channel.InsertarActualizarCreditMemoAsync(dsCreditMemo);
        }
        
        public ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarPurchaseInvoice(System.Data.DataSet dsPurchaseInvoice) {
            return base.Channel.InsertarActualizarPurchaseInvoice(dsPurchaseInvoice);
        }
        
        public System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarPurchaseInvoiceAsync(System.Data.DataSet dsPurchaseInvoice) {
            return base.Channel.InsertarActualizarPurchaseInvoiceAsync(dsPurchaseInvoice);
        }
        
        public ApplicationForm.IntegrationService.Respuesta[] InsertarActualizarPurchaseCreditMemo(System.Data.DataSet PurchaseCreditMemo) {
            return base.Channel.InsertarActualizarPurchaseCreditMemo(PurchaseCreditMemo);
        }
        
        public System.Threading.Tasks.Task<ApplicationForm.IntegrationService.Respuesta[]> InsertarActualizarPurchaseCreditMemoAsync(System.Data.DataSet PurchaseCreditMemo) {
            return base.Channel.InsertarActualizarPurchaseCreditMemoAsync(PurchaseCreditMemo);
        }
    }
}
