//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delfin.Principal.AppService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppService.IDelfinService")]
    public interface IDelfinService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/ExecuteSQL", ReplyAction="http://tempuri.org/IDelfinService/ExecuteSQLResponse")]
        System.Data.DataSet ExecuteSQL(string QueryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/ExecuteSQL", ReplyAction="http://tempuri.org/IDelfinService/ExecuteSQLResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ExecuteSQLAsync(string QueryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/NewExecuteSQL", ReplyAction="http://tempuri.org/IDelfinService/NewExecuteSQLResponse")]
        System.Data.DataSet NewExecuteSQL(string QueryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/NewExecuteSQL", ReplyAction="http://tempuri.org/IDelfinService/NewExecuteSQLResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> NewExecuteSQLAsync(string QueryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/ExecuteSQLNonQuery", ReplyAction="http://tempuri.org/IDelfinService/ExecuteSQLNonQueryResponse")]
        bool ExecuteSQLNonQuery(string QueryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/ExecuteSQLNonQuery", ReplyAction="http://tempuri.org/IDelfinService/ExecuteSQLNonQueryResponse")]
        System.Threading.Tasks.Task<bool> ExecuteSQLNonQueryAsync(string QueryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/NewExecuteSQLNonQuery", ReplyAction="http://tempuri.org/IDelfinService/NewExecuteSQLNonQueryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] NewExecuteSQLNonQuery(string QueryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/NewExecuteSQLNonQuery", ReplyAction="http://tempuri.org/IDelfinService/NewExecuteSQLNonQueryResponse")]
        System.Threading.Tasks.Task<object[]> NewExecuteSQLNonQueryAsync(string QueryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/GetActiveDirectoryObjects", ReplyAction="http://tempuri.org/IDelfinService/GetActiveDirectoryObjectsResponse")]
        System.Data.DataSet GetActiveDirectoryObjects(string DirectoryEntry, string DirectoryUserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/GetActiveDirectoryObjects", ReplyAction="http://tempuri.org/IDelfinService/GetActiveDirectoryObjectsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetActiveDirectoryObjectsAsync(string DirectoryEntry, string DirectoryUserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/UserValidation", ReplyAction="http://tempuri.org/IDelfinService/UserValidationResponse")]
        string UserValidation(string DirectoryEntry, string DirectoryUserName, string DirectoryPassword, string ErrorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/UserValidation", ReplyAction="http://tempuri.org/IDelfinService/UserValidationResponse")]
        System.Threading.Tasks.Task<string> UserValidationAsync(string DirectoryEntry, string DirectoryUserName, string DirectoryPassword, string ErrorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/GenerateNextSisVoucher", ReplyAction="http://tempuri.org/IDelfinService/GenerateNextSisVoucherResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] GenerateNextSisVoucher(string Company, System.Data.DataSet dsVoucher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/GenerateNextSisVoucher", ReplyAction="http://tempuri.org/IDelfinService/GenerateNextSisVoucherResponse")]
        System.Threading.Tasks.Task<object[]> GenerateNextSisVoucherAsync(string Company, System.Data.DataSet dsVoucher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/GenerateNextSisVoucherBCopy", ReplyAction="http://tempuri.org/IDelfinService/GenerateNextSisVoucherBCopyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] GenerateNextSisVoucherBCopy(string Company, System.Data.DataSet dsVoucher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/GenerateNextSisVoucherBCopy", ReplyAction="http://tempuri.org/IDelfinService/GenerateNextSisVoucherBCopyResponse")]
        System.Threading.Tasks.Task<object[]> GenerateNextSisVoucherBCopyAsync(string Company, System.Data.DataSet dsVoucher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/GenerateNextSoftVoucher", ReplyAction="http://tempuri.org/IDelfinService/GenerateNextSoftVoucherResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] GenerateNextSoftVoucher(System.Data.DataTable dtMovimiento, System.Data.DataTable dtCtaCte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/GenerateNextSoftVoucher", ReplyAction="http://tempuri.org/IDelfinService/GenerateNextSoftVoucherResponse")]
        System.Threading.Tasks.Task<object[]> GenerateNextSoftVoucherAsync(System.Data.DataTable dtMovimiento, System.Data.DataTable dtCtaCte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/InsertarContribuyente", ReplyAction="http://tempuri.org/IDelfinService/InsertarContribuyenteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] InsertarContribuyente(System.Data.DataTable dtSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/InsertarContribuyente", ReplyAction="http://tempuri.org/IDelfinService/InsertarContribuyenteResponse")]
        System.Threading.Tasks.Task<object[]> InsertarContribuyenteAsync(System.Data.DataTable dtSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/ActualizarContribuyente", ReplyAction="http://tempuri.org/IDelfinService/ActualizarContribuyenteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] ActualizarContribuyente(System.Data.DataTable dtSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/ActualizarContribuyente", ReplyAction="http://tempuri.org/IDelfinService/ActualizarContribuyenteResponse")]
        System.Threading.Tasks.Task<object[]> ActualizarContribuyenteAsync(System.Data.DataTable dtSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/UpdateTableWithBulkCopy", ReplyAction="http://tempuri.org/IDelfinService/UpdateTableWithBulkCopyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] UpdateTableWithBulkCopy(string Table, System.Data.DataTable dtSource, string ProcessType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/UpdateTableWithBulkCopy", ReplyAction="http://tempuri.org/IDelfinService/UpdateTableWithBulkCopyResponse")]
        System.Threading.Tasks.Task<object[]> UpdateTableWithBulkCopyAsync(string Table, System.Data.DataTable dtSource, string ProcessType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/UpdatingUsingTableAsParameter", ReplyAction="http://tempuri.org/IDelfinService/UpdatingUsingTableAsParameterResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] UpdatingUsingTableAsParameter(string StoreProcedure, System.Data.DataTable dtSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/UpdatingUsingTableAsParameter", ReplyAction="http://tempuri.org/IDelfinService/UpdatingUsingTableAsParameterResponse")]
        System.Threading.Tasks.Task<object[]> UpdatingUsingTableAsParameterAsync(string StoreProcedure, System.Data.DataTable dtSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/UpdatingWithTableAndParameters", ReplyAction="http://tempuri.org/IDelfinService/UpdatingWithTableAndParametersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] UpdatingWithTableAndParameters(string StoreProcedure, System.Data.DataTable dtSource, object[] Params, object[] Values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/UpdatingWithTableAndParameters", ReplyAction="http://tempuri.org/IDelfinService/UpdatingWithTableAndParametersResponse")]
        System.Threading.Tasks.Task<object[]> UpdatingWithTableAndParametersAsync(string StoreProcedure, System.Data.DataTable dtSource, object[] Params, object[] Values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/ExecuteStoreProcedure", ReplyAction="http://tempuri.org/IDelfinService/ExecuteStoreProcedureResponse")]
        System.Data.DataSet ExecuteStoreProcedure(string sp_name, string[][] sp_parameters, string sp_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/ExecuteStoreProcedure", ReplyAction="http://tempuri.org/IDelfinService/ExecuteStoreProcedureResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ExecuteStoreProcedureAsync(string sp_name, string[][] sp_parameters, string sp_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/InsertEvento", ReplyAction="http://tempuri.org/IDelfinService/InsertEventoResponse")]
        ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE InsertEvento(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/InsertEvento", ReplyAction="http://tempuri.org/IDelfinService/InsertEventoResponse")]
        System.Threading.Tasks.Task<ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE> InsertEventoAsync(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/UpdateEvento", ReplyAction="http://tempuri.org/IDelfinService/UpdateEventoResponse")]
        void UpdateEvento(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/UpdateEvento", ReplyAction="http://tempuri.org/IDelfinService/UpdateEventoResponse")]
        System.Threading.Tasks.Task UpdateEventoAsync(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/DeleteEvento", ReplyAction="http://tempuri.org/IDelfinService/DeleteEventoResponse")]
        void DeleteEvento(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelfinService/DeleteEvento", ReplyAction="http://tempuri.org/IDelfinService/DeleteEventoResponse")]
        System.Threading.Tasks.Task DeleteEventoAsync(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDelfinServiceChannel : Delfin.Principal.AppService.IDelfinService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DelfinServiceClient : System.ServiceModel.ClientBase<Delfin.Principal.AppService.IDelfinService>, Delfin.Principal.AppService.IDelfinService {
        
        public DelfinServiceClient() {
        }
        
        public DelfinServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DelfinServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DelfinServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DelfinServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ExecuteSQL(string QueryString) {
            return base.Channel.ExecuteSQL(QueryString);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ExecuteSQLAsync(string QueryString) {
            return base.Channel.ExecuteSQLAsync(QueryString);
        }
        
        public System.Data.DataSet NewExecuteSQL(string QueryString) {
            return base.Channel.NewExecuteSQL(QueryString);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> NewExecuteSQLAsync(string QueryString) {
            return base.Channel.NewExecuteSQLAsync(QueryString);
        }
        
        public bool ExecuteSQLNonQuery(string QueryString) {
            return base.Channel.ExecuteSQLNonQuery(QueryString);
        }
        
        public System.Threading.Tasks.Task<bool> ExecuteSQLNonQueryAsync(string QueryString) {
            return base.Channel.ExecuteSQLNonQueryAsync(QueryString);
        }
        
        public object[] NewExecuteSQLNonQuery(string QueryString) {
            return base.Channel.NewExecuteSQLNonQuery(QueryString);
        }
        
        public System.Threading.Tasks.Task<object[]> NewExecuteSQLNonQueryAsync(string QueryString) {
            return base.Channel.NewExecuteSQLNonQueryAsync(QueryString);
        }
        
        public System.Data.DataSet GetActiveDirectoryObjects(string DirectoryEntry, string DirectoryUserName) {
            return base.Channel.GetActiveDirectoryObjects(DirectoryEntry, DirectoryUserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetActiveDirectoryObjectsAsync(string DirectoryEntry, string DirectoryUserName) {
            return base.Channel.GetActiveDirectoryObjectsAsync(DirectoryEntry, DirectoryUserName);
        }
        
        public string UserValidation(string DirectoryEntry, string DirectoryUserName, string DirectoryPassword, string ErrorMessage) {
            return base.Channel.UserValidation(DirectoryEntry, DirectoryUserName, DirectoryPassword, ErrorMessage);
        }
        
        public System.Threading.Tasks.Task<string> UserValidationAsync(string DirectoryEntry, string DirectoryUserName, string DirectoryPassword, string ErrorMessage) {
            return base.Channel.UserValidationAsync(DirectoryEntry, DirectoryUserName, DirectoryPassword, ErrorMessage);
        }
        
        public object[] GenerateNextSisVoucher(string Company, System.Data.DataSet dsVoucher) {
            return base.Channel.GenerateNextSisVoucher(Company, dsVoucher);
        }
        
        public System.Threading.Tasks.Task<object[]> GenerateNextSisVoucherAsync(string Company, System.Data.DataSet dsVoucher) {
            return base.Channel.GenerateNextSisVoucherAsync(Company, dsVoucher);
        }
        
        public object[] GenerateNextSisVoucherBCopy(string Company, System.Data.DataSet dsVoucher) {
            return base.Channel.GenerateNextSisVoucherBCopy(Company, dsVoucher);
        }
        
        public System.Threading.Tasks.Task<object[]> GenerateNextSisVoucherBCopyAsync(string Company, System.Data.DataSet dsVoucher) {
            return base.Channel.GenerateNextSisVoucherBCopyAsync(Company, dsVoucher);
        }
        
        public object[] GenerateNextSoftVoucher(System.Data.DataTable dtMovimiento, System.Data.DataTable dtCtaCte) {
            return base.Channel.GenerateNextSoftVoucher(dtMovimiento, dtCtaCte);
        }
        
        public System.Threading.Tasks.Task<object[]> GenerateNextSoftVoucherAsync(System.Data.DataTable dtMovimiento, System.Data.DataTable dtCtaCte) {
            return base.Channel.GenerateNextSoftVoucherAsync(dtMovimiento, dtCtaCte);
        }
        
        public object[] InsertarContribuyente(System.Data.DataTable dtSource) {
            return base.Channel.InsertarContribuyente(dtSource);
        }
        
        public System.Threading.Tasks.Task<object[]> InsertarContribuyenteAsync(System.Data.DataTable dtSource) {
            return base.Channel.InsertarContribuyenteAsync(dtSource);
        }
        
        public object[] ActualizarContribuyente(System.Data.DataTable dtSource) {
            return base.Channel.ActualizarContribuyente(dtSource);
        }
        
        public System.Threading.Tasks.Task<object[]> ActualizarContribuyenteAsync(System.Data.DataTable dtSource) {
            return base.Channel.ActualizarContribuyenteAsync(dtSource);
        }
        
        public object[] UpdateTableWithBulkCopy(string Table, System.Data.DataTable dtSource, string ProcessType) {
            return base.Channel.UpdateTableWithBulkCopy(Table, dtSource, ProcessType);
        }
        
        public System.Threading.Tasks.Task<object[]> UpdateTableWithBulkCopyAsync(string Table, System.Data.DataTable dtSource, string ProcessType) {
            return base.Channel.UpdateTableWithBulkCopyAsync(Table, dtSource, ProcessType);
        }
        
        public object[] UpdatingUsingTableAsParameter(string StoreProcedure, System.Data.DataTable dtSource) {
            return base.Channel.UpdatingUsingTableAsParameter(StoreProcedure, dtSource);
        }
        
        public System.Threading.Tasks.Task<object[]> UpdatingUsingTableAsParameterAsync(string StoreProcedure, System.Data.DataTable dtSource) {
            return base.Channel.UpdatingUsingTableAsParameterAsync(StoreProcedure, dtSource);
        }
        
        public object[] UpdatingWithTableAndParameters(string StoreProcedure, System.Data.DataTable dtSource, object[] Params, object[] Values) {
            return base.Channel.UpdatingWithTableAndParameters(StoreProcedure, dtSource, Params, Values);
        }
        
        public System.Threading.Tasks.Task<object[]> UpdatingWithTableAndParametersAsync(string StoreProcedure, System.Data.DataTable dtSource, object[] Params, object[] Values) {
            return base.Channel.UpdatingWithTableAndParametersAsync(StoreProcedure, dtSource, Params, Values);
        }
        
        public System.Data.DataSet ExecuteStoreProcedure(string sp_name, string[][] sp_parameters, string sp_type) {
            return base.Channel.ExecuteStoreProcedure(sp_name, sp_parameters, sp_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ExecuteStoreProcedureAsync(string sp_name, string[][] sp_parameters, string sp_type) {
            return base.Channel.ExecuteStoreProcedureAsync(sp_name, sp_parameters, sp_type);
        }
        
        public ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE InsertEvento(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento) {
            return base.Channel.InsertEvento(oEvento);
        }
        
        public System.Threading.Tasks.Task<ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE> InsertEventoAsync(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento) {
            return base.Channel.InsertEventoAsync(oEvento);
        }
        
        public void UpdateEvento(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento) {
            base.Channel.UpdateEvento(oEvento);
        }
        
        public System.Threading.Tasks.Task UpdateEventoAsync(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento) {
            return base.Channel.UpdateEventoAsync(oEvento);
        }
        
        public void DeleteEvento(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento) {
            base.Channel.DeleteEvento(oEvento);
        }
        
        public System.Threading.Tasks.Task DeleteEventoAsync(ApplicationForm.AppService.COM_Det_Cotizacion_OV_EventosTareas_BE oEvento) {
            return base.Channel.DeleteEventoAsync(oEvento);
        }
    }
}
