'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace AppService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="COM_Det_Cotizacion_OV_EventosTareas_BE", [Namespace]:="http://schemas.datacontract.org/2004/07/Application.BusinessEntities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class COM_Det_Cotizacion_OV_EventosTareas_BE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecCreaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecModField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrCreaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrModField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCOT_NumeroField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCOT_TipoField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CONS_CodMODField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CONS_TabMODField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EVEN_CumplidaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EVEN_FechaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EVEN_ItemField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EVEN_ManualField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EVEN_ObservacionesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EVEN_UsuarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TIPO_CodEVEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TIPO_TabEVEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecCrea() As Date
            Get
                Return Me.AUDI_FecCreaField
            End Get
            Set
                If (Me.AUDI_FecCreaField.Equals(value) <> true) Then
                    Me.AUDI_FecCreaField = value
                    Me.RaisePropertyChanged("AUDI_FecCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecMod() As Date
            Get
                Return Me.AUDI_FecModField
            End Get
            Set
                If (Me.AUDI_FecModField.Equals(value) <> true) Then
                    Me.AUDI_FecModField = value
                    Me.RaisePropertyChanged("AUDI_FecMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrCrea() As String
            Get
                Return Me.AUDI_UsrCreaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrCreaField, value) <> true) Then
                    Me.AUDI_UsrCreaField = value
                    Me.RaisePropertyChanged("AUDI_UsrCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrMod() As String
            Get
                Return Me.AUDI_UsrModField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrModField, value) <> true) Then
                    Me.AUDI_UsrModField = value
                    Me.RaisePropertyChanged("AUDI_UsrMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCOT_Numero() As Integer
            Get
                Return Me.CCOT_NumeroField
            End Get
            Set
                If (Me.CCOT_NumeroField.Equals(value) <> true) Then
                    Me.CCOT_NumeroField = value
                    Me.RaisePropertyChanged("CCOT_Numero")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCOT_Tipo() As Short
            Get
                Return Me.CCOT_TipoField
            End Get
            Set
                If (Me.CCOT_TipoField.Equals(value) <> true) Then
                    Me.CCOT_TipoField = value
                    Me.RaisePropertyChanged("CCOT_Tipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CONS_CodMOD() As String
            Get
                Return Me.CONS_CodMODField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CONS_CodMODField, value) <> true) Then
                    Me.CONS_CodMODField = value
                    Me.RaisePropertyChanged("CONS_CodMOD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CONS_TabMOD() As String
            Get
                Return Me.CONS_TabMODField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CONS_TabMODField, value) <> true) Then
                    Me.CONS_TabMODField = value
                    Me.RaisePropertyChanged("CONS_TabMOD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EVEN_Cumplida() As Boolean
            Get
                Return Me.EVEN_CumplidaField
            End Get
            Set
                If (Me.EVEN_CumplidaField.Equals(value) <> true) Then
                    Me.EVEN_CumplidaField = value
                    Me.RaisePropertyChanged("EVEN_Cumplida")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EVEN_Fecha() As Date
            Get
                Return Me.EVEN_FechaField
            End Get
            Set
                If (Me.EVEN_FechaField.Equals(value) <> true) Then
                    Me.EVEN_FechaField = value
                    Me.RaisePropertyChanged("EVEN_Fecha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EVEN_Item() As Short
            Get
                Return Me.EVEN_ItemField
            End Get
            Set
                If (Me.EVEN_ItemField.Equals(value) <> true) Then
                    Me.EVEN_ItemField = value
                    Me.RaisePropertyChanged("EVEN_Item")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EVEN_Manual() As Boolean
            Get
                Return Me.EVEN_ManualField
            End Get
            Set
                If (Me.EVEN_ManualField.Equals(value) <> true) Then
                    Me.EVEN_ManualField = value
                    Me.RaisePropertyChanged("EVEN_Manual")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EVEN_Observaciones() As String
            Get
                Return Me.EVEN_ObservacionesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EVEN_ObservacionesField, value) <> true) Then
                    Me.EVEN_ObservacionesField = value
                    Me.RaisePropertyChanged("EVEN_Observaciones")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EVEN_Usuario() As String
            Get
                Return Me.EVEN_UsuarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EVEN_UsuarioField, value) <> true) Then
                    Me.EVEN_UsuarioField = value
                    Me.RaisePropertyChanged("EVEN_Usuario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TIPO_CodEVE() As String
            Get
                Return Me.TIPO_CodEVEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TIPO_CodEVEField, value) <> true) Then
                    Me.TIPO_CodEVEField = value
                    Me.RaisePropertyChanged("TIPO_CodEVE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TIPO_TabEVE() As String
            Get
                Return Me.TIPO_TabEVEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TIPO_TabEVEField, value) <> true) Then
                    Me.TIPO_TabEVEField = value
                    Me.RaisePropertyChanged("TIPO_TabEVE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AppService.IDelfinService")>  _
    Public Interface IDelfinService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/ExecuteSQL", ReplyAction:="http://tempuri.org/IDelfinService/ExecuteSQLResponse")>  _
        Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/ExecuteSQL", ReplyAction:="http://tempuri.org/IDelfinService/ExecuteSQLResponse")>  _
        Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/NewExecuteSQL", ReplyAction:="http://tempuri.org/IDelfinService/NewExecuteSQLResponse")>  _
        Function NewExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/NewExecuteSQL", ReplyAction:="http://tempuri.org/IDelfinService/NewExecuteSQLResponse")>  _
        Function NewExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IDelfinService/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQuery(ByVal QueryString As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IDelfinService/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/NewExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IDelfinService/NewExecuteSQLNonQueryResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function NewExecuteSQLNonQuery(ByVal QueryString As String) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/NewExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IDelfinService/NewExecuteSQLNonQueryResponse")>  _
        Function NewExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/GetActiveDirectoryObjects", ReplyAction:="http://tempuri.org/IDelfinService/GetActiveDirectoryObjectsResponse")>  _
        Function GetActiveDirectoryObjects(ByVal DirectoryEntry As String, ByVal DirectoryUserName As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/GetActiveDirectoryObjects", ReplyAction:="http://tempuri.org/IDelfinService/GetActiveDirectoryObjectsResponse")>  _
        Function GetActiveDirectoryObjectsAsync(ByVal DirectoryEntry As String, ByVal DirectoryUserName As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UserValidation", ReplyAction:="http://tempuri.org/IDelfinService/UserValidationResponse")>  _
        Function UserValidation(ByVal DirectoryEntry As String, ByVal DirectoryUserName As String, ByVal DirectoryPassword As String, ByVal ErrorMessage As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UserValidation", ReplyAction:="http://tempuri.org/IDelfinService/UserValidationResponse")>  _
        Function UserValidationAsync(ByVal DirectoryEntry As String, ByVal DirectoryUserName As String, ByVal DirectoryPassword As String, ByVal ErrorMessage As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/GenerateNextSisVoucher", ReplyAction:="http://tempuri.org/IDelfinService/GenerateNextSisVoucherResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function GenerateNextSisVoucher(ByVal Company As String, ByVal dsVoucher As System.Data.DataSet) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/GenerateNextSisVoucher", ReplyAction:="http://tempuri.org/IDelfinService/GenerateNextSisVoucherResponse")>  _
        Function GenerateNextSisVoucherAsync(ByVal Company As String, ByVal dsVoucher As System.Data.DataSet) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/GenerateNextSisVoucherBCopy", ReplyAction:="http://tempuri.org/IDelfinService/GenerateNextSisVoucherBCopyResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function GenerateNextSisVoucherBCopy(ByVal Company As String, ByVal dsVoucher As System.Data.DataSet) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/GenerateNextSisVoucherBCopy", ReplyAction:="http://tempuri.org/IDelfinService/GenerateNextSisVoucherBCopyResponse")>  _
        Function GenerateNextSisVoucherBCopyAsync(ByVal Company As String, ByVal dsVoucher As System.Data.DataSet) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/GenerateNextSoftVoucher", ReplyAction:="http://tempuri.org/IDelfinService/GenerateNextSoftVoucherResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function GenerateNextSoftVoucher(ByVal dtMovimiento As System.Data.DataTable, ByVal dtCtaCte As System.Data.DataTable) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/GenerateNextSoftVoucher", ReplyAction:="http://tempuri.org/IDelfinService/GenerateNextSoftVoucherResponse")>  _
        Function GenerateNextSoftVoucherAsync(ByVal dtMovimiento As System.Data.DataTable, ByVal dtCtaCte As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/InsertarContribuyente", ReplyAction:="http://tempuri.org/IDelfinService/InsertarContribuyenteResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function InsertarContribuyente(ByVal dtSource As System.Data.DataTable) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/InsertarContribuyente", ReplyAction:="http://tempuri.org/IDelfinService/InsertarContribuyenteResponse")>  _
        Function InsertarContribuyenteAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/ActualizarContribuyente", ReplyAction:="http://tempuri.org/IDelfinService/ActualizarContribuyenteResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function ActualizarContribuyente(ByVal dtSource As System.Data.DataTable) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/ActualizarContribuyente", ReplyAction:="http://tempuri.org/IDelfinService/ActualizarContribuyenteResponse")>  _
        Function ActualizarContribuyenteAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UpdateTableWithBulkCopy", ReplyAction:="http://tempuri.org/IDelfinService/UpdateTableWithBulkCopyResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function UpdateTableWithBulkCopy(ByVal Table As String, ByVal dtSource As System.Data.DataTable, ByVal ProcessType As String) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UpdateTableWithBulkCopy", ReplyAction:="http://tempuri.org/IDelfinService/UpdateTableWithBulkCopyResponse")>  _
        Function UpdateTableWithBulkCopyAsync(ByVal Table As String, ByVal dtSource As System.Data.DataTable, ByVal ProcessType As String) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UpdatingUsingTableAsParameter", ReplyAction:="http://tempuri.org/IDelfinService/UpdatingUsingTableAsParameterResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function UpdatingUsingTableAsParameter(ByVal StoreProcedure As String, ByVal dtSource As System.Data.DataTable) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UpdatingUsingTableAsParameter", ReplyAction:="http://tempuri.org/IDelfinService/UpdatingUsingTableAsParameterResponse")>  _
        Function UpdatingUsingTableAsParameterAsync(ByVal StoreProcedure As String, ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UpdatingWithTableAndParameters", ReplyAction:="http://tempuri.org/IDelfinService/UpdatingWithTableAndParametersResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function UpdatingWithTableAndParameters(ByVal StoreProcedure As String, ByVal dtSource As System.Data.DataTable, ByVal Params() As Object, ByVal Values() As Object) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UpdatingWithTableAndParameters", ReplyAction:="http://tempuri.org/IDelfinService/UpdatingWithTableAndParametersResponse")>  _
        Function UpdatingWithTableAndParametersAsync(ByVal StoreProcedure As String, ByVal dtSource As System.Data.DataTable, ByVal Params() As Object, ByVal Values() As Object) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/ExecuteStoreProcedure", ReplyAction:="http://tempuri.org/IDelfinService/ExecuteStoreProcedureResponse")>  _
        Function ExecuteStoreProcedure(ByVal sp_name As String, ByVal sp_parameters()() As String, ByVal sp_type As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/ExecuteStoreProcedure", ReplyAction:="http://tempuri.org/IDelfinService/ExecuteStoreProcedureResponse")>  _
        Function ExecuteStoreProcedureAsync(ByVal sp_name As String, ByVal sp_parameters()() As String, ByVal sp_type As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/InsertEvento", ReplyAction:="http://tempuri.org/IDelfinService/InsertEventoResponse")>  _
        Function InsertEvento(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/InsertEvento", ReplyAction:="http://tempuri.org/IDelfinService/InsertEventoResponse")>  _
        Function InsertEventoAsync(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) As System.Threading.Tasks.Task(Of AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UpdateEvento", ReplyAction:="http://tempuri.org/IDelfinService/UpdateEventoResponse")>  _
        Sub UpdateEvento(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UpdateEvento", ReplyAction:="http://tempuri.org/IDelfinService/UpdateEventoResponse")>  _
        Function UpdateEventoAsync(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/DeleteEvento", ReplyAction:="http://tempuri.org/IDelfinService/DeleteEventoResponse")>  _
        Sub DeleteEvento(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/DeleteEvento", ReplyAction:="http://tempuri.org/IDelfinService/DeleteEventoResponse")>  _
        Function DeleteEventoAsync(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/InsertLogisticOperation", ReplyAction:="http://tempuri.org/IDelfinService/InsertLogisticOperationResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function InsertLogisticOperation(ByVal dsLogisticOperation As System.Data.DataSet) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/InsertLogisticOperation", ReplyAction:="http://tempuri.org/IDelfinService/InsertLogisticOperationResponse")>  _
        Function InsertLogisticOperationAsync(ByVal dsLogisticOperation As System.Data.DataSet) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UpdateLogisticOperation", ReplyAction:="http://tempuri.org/IDelfinService/UpdateLogisticOperationResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function UpdateLogisticOperation(ByVal dsLogisticOperation As System.Data.DataSet, ByVal dtOriginalDetail As System.Data.DataTable, ByVal dtOriginalChangeControl As System.Data.DataTable) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/UpdateLogisticOperation", ReplyAction:="http://tempuri.org/IDelfinService/UpdateLogisticOperationResponse")>  _
        Function UpdateLogisticOperationAsync(ByVal dsLogisticOperation As System.Data.DataSet, ByVal dtOriginalDetail As System.Data.DataTable, ByVal dtOriginalChangeControl As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/PreFacturar", ReplyAction:="http://tempuri.org/IDelfinService/PreFacturarResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AppService.COM_Det_Cotizacion_OV_EventosTareas_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function PreFacturar(ByVal COPE_Codigo As Integer, ByVal dsDocumentoVenta As System.Data.DataSet) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/PreFacturar", ReplyAction:="http://tempuri.org/IDelfinService/PreFacturarResponse")>  _
        Function PreFacturarAsync(ByVal COPE_Codigo As Integer, ByVal dsDocumentoVenta As System.Data.DataSet) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/InsertDocumentsProvider", ReplyAction:="http://tempuri.org/IDelfinService/InsertDocumentsProviderResponse")>  _
        Function InsertDocumentsProvider(ByVal dsDocumentsProvider As System.Data.DataSet, ByVal Items As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDelfinService/InsertDocumentsProvider", ReplyAction:="http://tempuri.org/IDelfinService/InsertDocumentsProviderResponse")>  _
        Function InsertDocumentsProviderAsync(ByVal dsDocumentsProvider As System.Data.DataSet, ByVal Items As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IDelfinServiceChannel
        Inherits AppService.IDelfinService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DelfinServiceClient
        Inherits System.ServiceModel.ClientBase(Of AppService.IDelfinService)
        Implements AppService.IDelfinService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements AppService.IDelfinService.ExecuteSQL
            Return MyBase.Channel.ExecuteSQL(QueryString)
        End Function
        
        Public Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements AppService.IDelfinService.ExecuteSQLAsync
            Return MyBase.Channel.ExecuteSQLAsync(QueryString)
        End Function
        
        Public Function NewExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements AppService.IDelfinService.NewExecuteSQL
            Return MyBase.Channel.NewExecuteSQL(QueryString)
        End Function
        
        Public Function NewExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements AppService.IDelfinService.NewExecuteSQLAsync
            Return MyBase.Channel.NewExecuteSQLAsync(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQuery(ByVal QueryString As String) As Boolean Implements AppService.IDelfinService.ExecuteSQLNonQuery
            Return MyBase.Channel.ExecuteSQLNonQuery(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IDelfinService.ExecuteSQLNonQueryAsync
            Return MyBase.Channel.ExecuteSQLNonQueryAsync(QueryString)
        End Function
        
        Public Function NewExecuteSQLNonQuery(ByVal QueryString As String) As Object() Implements AppService.IDelfinService.NewExecuteSQLNonQuery
            Return MyBase.Channel.NewExecuteSQLNonQuery(QueryString)
        End Function
        
        Public Function NewExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.NewExecuteSQLNonQueryAsync
            Return MyBase.Channel.NewExecuteSQLNonQueryAsync(QueryString)
        End Function
        
        Public Function GetActiveDirectoryObjects(ByVal DirectoryEntry As String, ByVal DirectoryUserName As String) As System.Data.DataSet Implements AppService.IDelfinService.GetActiveDirectoryObjects
            Return MyBase.Channel.GetActiveDirectoryObjects(DirectoryEntry, DirectoryUserName)
        End Function
        
        Public Function GetActiveDirectoryObjectsAsync(ByVal DirectoryEntry As String, ByVal DirectoryUserName As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements AppService.IDelfinService.GetActiveDirectoryObjectsAsync
            Return MyBase.Channel.GetActiveDirectoryObjectsAsync(DirectoryEntry, DirectoryUserName)
        End Function
        
        Public Function UserValidation(ByVal DirectoryEntry As String, ByVal DirectoryUserName As String, ByVal DirectoryPassword As String, ByVal ErrorMessage As String) As String Implements AppService.IDelfinService.UserValidation
            Return MyBase.Channel.UserValidation(DirectoryEntry, DirectoryUserName, DirectoryPassword, ErrorMessage)
        End Function
        
        Public Function UserValidationAsync(ByVal DirectoryEntry As String, ByVal DirectoryUserName As String, ByVal DirectoryPassword As String, ByVal ErrorMessage As String) As System.Threading.Tasks.Task(Of String) Implements AppService.IDelfinService.UserValidationAsync
            Return MyBase.Channel.UserValidationAsync(DirectoryEntry, DirectoryUserName, DirectoryPassword, ErrorMessage)
        End Function
        
        Public Function GenerateNextSisVoucher(ByVal Company As String, ByVal dsVoucher As System.Data.DataSet) As Object() Implements AppService.IDelfinService.GenerateNextSisVoucher
            Return MyBase.Channel.GenerateNextSisVoucher(Company, dsVoucher)
        End Function
        
        Public Function GenerateNextSisVoucherAsync(ByVal Company As String, ByVal dsVoucher As System.Data.DataSet) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.GenerateNextSisVoucherAsync
            Return MyBase.Channel.GenerateNextSisVoucherAsync(Company, dsVoucher)
        End Function
        
        Public Function GenerateNextSisVoucherBCopy(ByVal Company As String, ByVal dsVoucher As System.Data.DataSet) As Object() Implements AppService.IDelfinService.GenerateNextSisVoucherBCopy
            Return MyBase.Channel.GenerateNextSisVoucherBCopy(Company, dsVoucher)
        End Function
        
        Public Function GenerateNextSisVoucherBCopyAsync(ByVal Company As String, ByVal dsVoucher As System.Data.DataSet) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.GenerateNextSisVoucherBCopyAsync
            Return MyBase.Channel.GenerateNextSisVoucherBCopyAsync(Company, dsVoucher)
        End Function
        
        Public Function GenerateNextSoftVoucher(ByVal dtMovimiento As System.Data.DataTable, ByVal dtCtaCte As System.Data.DataTable) As Object() Implements AppService.IDelfinService.GenerateNextSoftVoucher
            Return MyBase.Channel.GenerateNextSoftVoucher(dtMovimiento, dtCtaCte)
        End Function
        
        Public Function GenerateNextSoftVoucherAsync(ByVal dtMovimiento As System.Data.DataTable, ByVal dtCtaCte As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.GenerateNextSoftVoucherAsync
            Return MyBase.Channel.GenerateNextSoftVoucherAsync(dtMovimiento, dtCtaCte)
        End Function
        
        Public Function InsertarContribuyente(ByVal dtSource As System.Data.DataTable) As Object() Implements AppService.IDelfinService.InsertarContribuyente
            Return MyBase.Channel.InsertarContribuyente(dtSource)
        End Function
        
        Public Function InsertarContribuyenteAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.InsertarContribuyenteAsync
            Return MyBase.Channel.InsertarContribuyenteAsync(dtSource)
        End Function
        
        Public Function ActualizarContribuyente(ByVal dtSource As System.Data.DataTable) As Object() Implements AppService.IDelfinService.ActualizarContribuyente
            Return MyBase.Channel.ActualizarContribuyente(dtSource)
        End Function
        
        Public Function ActualizarContribuyenteAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.ActualizarContribuyenteAsync
            Return MyBase.Channel.ActualizarContribuyenteAsync(dtSource)
        End Function
        
        Public Function UpdateTableWithBulkCopy(ByVal Table As String, ByVal dtSource As System.Data.DataTable, ByVal ProcessType As String) As Object() Implements AppService.IDelfinService.UpdateTableWithBulkCopy
            Return MyBase.Channel.UpdateTableWithBulkCopy(Table, dtSource, ProcessType)
        End Function
        
        Public Function UpdateTableWithBulkCopyAsync(ByVal Table As String, ByVal dtSource As System.Data.DataTable, ByVal ProcessType As String) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.UpdateTableWithBulkCopyAsync
            Return MyBase.Channel.UpdateTableWithBulkCopyAsync(Table, dtSource, ProcessType)
        End Function
        
        Public Function UpdatingUsingTableAsParameter(ByVal StoreProcedure As String, ByVal dtSource As System.Data.DataTable) As Object() Implements AppService.IDelfinService.UpdatingUsingTableAsParameter
            Return MyBase.Channel.UpdatingUsingTableAsParameter(StoreProcedure, dtSource)
        End Function
        
        Public Function UpdatingUsingTableAsParameterAsync(ByVal StoreProcedure As String, ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.UpdatingUsingTableAsParameterAsync
            Return MyBase.Channel.UpdatingUsingTableAsParameterAsync(StoreProcedure, dtSource)
        End Function
        
        Public Function UpdatingWithTableAndParameters(ByVal StoreProcedure As String, ByVal dtSource As System.Data.DataTable, ByVal Params() As Object, ByVal Values() As Object) As Object() Implements AppService.IDelfinService.UpdatingWithTableAndParameters
            Return MyBase.Channel.UpdatingWithTableAndParameters(StoreProcedure, dtSource, Params, Values)
        End Function
        
        Public Function UpdatingWithTableAndParametersAsync(ByVal StoreProcedure As String, ByVal dtSource As System.Data.DataTable, ByVal Params() As Object, ByVal Values() As Object) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.UpdatingWithTableAndParametersAsync
            Return MyBase.Channel.UpdatingWithTableAndParametersAsync(StoreProcedure, dtSource, Params, Values)
        End Function
        
        Public Function ExecuteStoreProcedure(ByVal sp_name As String, ByVal sp_parameters()() As String, ByVal sp_type As String) As System.Data.DataSet Implements AppService.IDelfinService.ExecuteStoreProcedure
            Return MyBase.Channel.ExecuteStoreProcedure(sp_name, sp_parameters, sp_type)
        End Function
        
        Public Function ExecuteStoreProcedureAsync(ByVal sp_name As String, ByVal sp_parameters()() As String, ByVal sp_type As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements AppService.IDelfinService.ExecuteStoreProcedureAsync
            Return MyBase.Channel.ExecuteStoreProcedureAsync(sp_name, sp_parameters, sp_type)
        End Function
        
        Public Function InsertEvento(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE Implements AppService.IDelfinService.InsertEvento
            Return MyBase.Channel.InsertEvento(oEvento)
        End Function
        
        Public Function InsertEventoAsync(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) As System.Threading.Tasks.Task(Of AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) Implements AppService.IDelfinService.InsertEventoAsync
            Return MyBase.Channel.InsertEventoAsync(oEvento)
        End Function
        
        Public Sub UpdateEvento(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) Implements AppService.IDelfinService.UpdateEvento
            MyBase.Channel.UpdateEvento(oEvento)
        End Sub
        
        Public Function UpdateEventoAsync(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) As System.Threading.Tasks.Task Implements AppService.IDelfinService.UpdateEventoAsync
            Return MyBase.Channel.UpdateEventoAsync(oEvento)
        End Function
        
        Public Sub DeleteEvento(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) Implements AppService.IDelfinService.DeleteEvento
            MyBase.Channel.DeleteEvento(oEvento)
        End Sub
        
        Public Function DeleteEventoAsync(ByVal oEvento As AppService.COM_Det_Cotizacion_OV_EventosTareas_BE) As System.Threading.Tasks.Task Implements AppService.IDelfinService.DeleteEventoAsync
            Return MyBase.Channel.DeleteEventoAsync(oEvento)
        End Function
        
        Public Function InsertLogisticOperation(ByVal dsLogisticOperation As System.Data.DataSet) As Object() Implements AppService.IDelfinService.InsertLogisticOperation
            Return MyBase.Channel.InsertLogisticOperation(dsLogisticOperation)
        End Function
        
        Public Function InsertLogisticOperationAsync(ByVal dsLogisticOperation As System.Data.DataSet) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.InsertLogisticOperationAsync
            Return MyBase.Channel.InsertLogisticOperationAsync(dsLogisticOperation)
        End Function
        
        Public Function UpdateLogisticOperation(ByVal dsLogisticOperation As System.Data.DataSet, ByVal dtOriginalDetail As System.Data.DataTable, ByVal dtOriginalChangeControl As System.Data.DataTable) As Object() Implements AppService.IDelfinService.UpdateLogisticOperation
            Return MyBase.Channel.UpdateLogisticOperation(dsLogisticOperation, dtOriginalDetail, dtOriginalChangeControl)
        End Function
        
        Public Function UpdateLogisticOperationAsync(ByVal dsLogisticOperation As System.Data.DataSet, ByVal dtOriginalDetail As System.Data.DataTable, ByVal dtOriginalChangeControl As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.UpdateLogisticOperationAsync
            Return MyBase.Channel.UpdateLogisticOperationAsync(dsLogisticOperation, dtOriginalDetail, dtOriginalChangeControl)
        End Function
        
        Public Function PreFacturar(ByVal COPE_Codigo As Integer, ByVal dsDocumentoVenta As System.Data.DataSet) As Object() Implements AppService.IDelfinService.PreFacturar
            Return MyBase.Channel.PreFacturar(COPE_Codigo, dsDocumentoVenta)
        End Function
        
        Public Function PreFacturarAsync(ByVal COPE_Codigo As Integer, ByVal dsDocumentoVenta As System.Data.DataSet) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IDelfinService.PreFacturarAsync
            Return MyBase.Channel.PreFacturarAsync(COPE_Codigo, dsDocumentoVenta)
        End Function
        
        Public Function InsertDocumentsProvider(ByVal dsDocumentsProvider As System.Data.DataSet, ByVal Items As String) As String Implements AppService.IDelfinService.InsertDocumentsProvider
            Return MyBase.Channel.InsertDocumentsProvider(dsDocumentsProvider, Items)
        End Function
        
        Public Function InsertDocumentsProviderAsync(ByVal dsDocumentsProvider As System.Data.DataSet, ByVal Items As String) As System.Threading.Tasks.Task(Of String) Implements AppService.IDelfinService.InsertDocumentsProviderAsync
            Return MyBase.Channel.InsertDocumentsProviderAsync(dsDocumentsProvider, Items)
        End Function
    End Class
End Namespace
