'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PorticoService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InputConfiguration", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InputConfiguration
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInputConfigurationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInputTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageConfigurationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InputConfigurationDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcessFileField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As Date
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As Date
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInputConfiguration() As Integer
            Get
                Return Me.IdInputConfigurationField
            End Get
            Set
                If (Me.IdInputConfigurationField.Equals(value) <> true) Then
                    Me.IdInputConfigurationField = value
                    Me.RaisePropertyChanged("IdInputConfiguration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInputType() As Integer
            Get
                Return Me.IdInputTypeField
            End Get
            Set
                If (Me.IdInputTypeField.Equals(value) <> true) Then
                    Me.IdInputTypeField = value
                    Me.RaisePropertyChanged("IdInputType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageConfiguration() As Integer
            Get
                Return Me.IdMessageConfigurationField
            End Get
            Set
                If (Me.IdMessageConfigurationField.Equals(value) <> true) Then
                    Me.IdMessageConfigurationField = value
                    Me.RaisePropertyChanged("IdMessageConfiguration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InputConfigurationDescription() As String
            Get
                Return Me.InputConfigurationDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InputConfigurationDescriptionField, value) <> true) Then
                    Me.InputConfigurationDescriptionField = value
                    Me.RaisePropertyChanged("InputConfigurationDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcessFile() As String
            Get
                Return Me.ProcessFileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcessFileField, value) <> true) Then
                    Me.ProcessFileField = value
                    Me.RaisePropertyChanged("ProcessFile")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InputSubject", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InputSubject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageConfigurationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageSubjectField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubjectIdentifierField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As Date
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As Date
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageConfiguration() As Integer
            Get
                Return Me.IdMessageConfigurationField
            End Get
            Set
                If (Me.IdMessageConfigurationField.Equals(value) <> true) Then
                    Me.IdMessageConfigurationField = value
                    Me.RaisePropertyChanged("IdMessageConfiguration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageSubject() As Integer
            Get
                Return Me.IdMessageSubjectField
            End Get
            Set
                If (Me.IdMessageSubjectField.Equals(value) <> true) Then
                    Me.IdMessageSubjectField = value
                    Me.RaisePropertyChanged("IdMessageSubject")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubjectIdentifier() As String
            Get
                Return Me.SubjectIdentifierField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubjectIdentifierField, value) <> true) Then
                    Me.SubjectIdentifierField = value
                    Me.RaisePropertyChanged("SubjectIdentifier")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InputType", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InputType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInputTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InputTypeDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As Date
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As Date
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInputType() As Integer
            Get
                Return Me.IdInputTypeField
            End Get
            Set
                If (Me.IdInputTypeField.Equals(value) <> true) Then
                    Me.IdInputTypeField = value
                    Me.RaisePropertyChanged("IdInputType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InputTypeDescription() As String
            Get
                Return Me.InputTypeDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InputTypeDescriptionField, value) <> true) Then
                    Me.InputTypeDescriptionField = value
                    Me.RaisePropertyChanged("InputTypeDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MessageConfiguration", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MessageConfiguration
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AttachedFilesField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BlindCopyRecipientsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopyRecipientsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomizedQueryField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInputTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageConfigurationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageFileField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RecipientsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AttachedFiles() As Byte()
            Get
                Return Me.AttachedFilesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AttachedFilesField, value) <> true) Then
                    Me.AttachedFilesField = value
                    Me.RaisePropertyChanged("AttachedFiles")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BlindCopyRecipients() As String
            Get
                Return Me.BlindCopyRecipientsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BlindCopyRecipientsField, value) <> true) Then
                    Me.BlindCopyRecipientsField = value
                    Me.RaisePropertyChanged("BlindCopyRecipients")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CopyRecipients() As String
            Get
                Return Me.CopyRecipientsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopyRecipientsField, value) <> true) Then
                    Me.CopyRecipientsField = value
                    Me.RaisePropertyChanged("CopyRecipients")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomizedQuery() As String
            Get
                Return Me.CustomizedQueryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomizedQueryField, value) <> true) Then
                    Me.CustomizedQueryField = value
                    Me.RaisePropertyChanged("CustomizedQuery")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As Date
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As Date
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInputType() As Integer
            Get
                Return Me.IdInputTypeField
            End Get
            Set
                If (Me.IdInputTypeField.Equals(value) <> true) Then
                    Me.IdInputTypeField = value
                    Me.RaisePropertyChanged("IdInputType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageConfiguration() As Integer
            Get
                Return Me.IdMessageConfigurationField
            End Get
            Set
                If (Me.IdMessageConfigurationField.Equals(value) <> true) Then
                    Me.IdMessageConfigurationField = value
                    Me.RaisePropertyChanged("IdMessageConfiguration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Image() As Byte()
            Get
                Return Me.ImageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageField, value) <> true) Then
                    Me.ImageField = value
                    Me.RaisePropertyChanged("Image")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageFile() As Byte()
            Get
                Return Me.ImageFileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageFileField, value) <> true) Then
                    Me.ImageFileField = value
                    Me.RaisePropertyChanged("ImageFile")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Recipients() As String
            Get
                Return Me.RecipientsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RecipientsField, value) <> true) Then
                    Me.RecipientsField = value
                    Me.RaisePropertyChanged("Recipients")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MessageLayout", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MessageLayout
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInputConfigurationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageLayoutField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageStructureField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageTextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidFromField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidToField As System.Nullable(Of Date)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As System.Nullable(Of Date)
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As System.Nullable(Of Date)
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInputConfiguration() As Integer
            Get
                Return Me.IdInputConfigurationField
            End Get
            Set
                If (Me.IdInputConfigurationField.Equals(value) <> true) Then
                    Me.IdInputConfigurationField = value
                    Me.RaisePropertyChanged("IdInputConfiguration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageLayout() As Integer
            Get
                Return Me.IdMessageLayoutField
            End Get
            Set
                If (Me.IdMessageLayoutField.Equals(value) <> true) Then
                    Me.IdMessageLayoutField = value
                    Me.RaisePropertyChanged("IdMessageLayout")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageStructure() As Integer
            Get
                Return Me.IdMessageStructureField
            End Get
            Set
                If (Me.IdMessageStructureField.Equals(value) <> true) Then
                    Me.IdMessageStructureField = value
                    Me.RaisePropertyChanged("IdMessageStructure")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MessageText() As String
            Get
                Return Me.MessageTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageTextField, value) <> true) Then
                    Me.MessageTextField = value
                    Me.RaisePropertyChanged("MessageText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValidFrom() As System.Nullable(Of Date)
            Get
                Return Me.ValidFromField
            End Get
            Set
                If (Me.ValidFromField.Equals(value) <> true) Then
                    Me.ValidFromField = value
                    Me.RaisePropertyChanged("ValidFrom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValidTo() As System.Nullable(Of Date)
            Get
                Return Me.ValidToField
            End Get
            Set
                If (Me.ValidToField.Equals(value) <> true) Then
                    Me.ValidToField = value
                    Me.RaisePropertyChanged("ValidTo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MessageStructure", [Namespace]:="http://schemas.datacontract.org/2004/07/MailBot.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MessageStructure
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateUpdateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMessageStructureField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IndexLocationField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageStructureDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SignatureField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCreateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserUpdateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreate() As Date
            Get
                Return Me.DateCreateField
            End Get
            Set
                If (Me.DateCreateField.Equals(value) <> true) Then
                    Me.DateCreateField = value
                    Me.RaisePropertyChanged("DateCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateUpdate() As Date
            Get
                Return Me.DateUpdateField
            End Get
            Set
                If (Me.DateUpdateField.Equals(value) <> true) Then
                    Me.DateUpdateField = value
                    Me.RaisePropertyChanged("DateUpdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMessageStructure() As Integer
            Get
                Return Me.IdMessageStructureField
            End Get
            Set
                If (Me.IdMessageStructureField.Equals(value) <> true) Then
                    Me.IdMessageStructureField = value
                    Me.RaisePropertyChanged("IdMessageStructure")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IndexLocation() As Integer
            Get
                Return Me.IndexLocationField
            End Get
            Set
                If (Me.IndexLocationField.Equals(value) <> true) Then
                    Me.IndexLocationField = value
                    Me.RaisePropertyChanged("IndexLocation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MessageStructureDescription() As String
            Get
                Return Me.MessageStructureDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageStructureDescriptionField, value) <> true) Then
                    Me.MessageStructureDescriptionField = value
                    Me.RaisePropertyChanged("MessageStructureDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Signature() As Boolean
            Get
                Return Me.SignatureField
            End Get
            Set
                If (Me.SignatureField.Equals(value) <> true) Then
                    Me.SignatureField = value
                    Me.RaisePropertyChanged("Signature")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCreate() As String
            Get
                Return Me.UserCreateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCreateField, value) <> true) Then
                    Me.UserCreateField = value
                    Me.RaisePropertyChanged("UserCreate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserUpdate() As String
            Get
                Return Me.UserUpdateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserUpdateField, value) <> true) Then
                    Me.UserUpdateField = value
                    Me.RaisePropertyChanged("UserUpdate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PorticoService.IPortico")>  _
    Public Interface IPortico
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/ExecuteSQL", ReplyAction:="http://tempuri.org/IPortico/ExecuteSQLResponse")>  _
        Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/ExecuteSQL", ReplyAction:="http://tempuri.org/IPortico/ExecuteSQLResponse")>  _
        Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/NewExecuteSQL", ReplyAction:="http://tempuri.org/IPortico/NewExecuteSQLResponse")>  _
        Function NewExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/NewExecuteSQL", ReplyAction:="http://tempuri.org/IPortico/NewExecuteSQLResponse")>  _
        Function NewExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IPortico/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQuery(ByVal QueryString As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IPortico/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/NewExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IPortico/NewExecuteSQLNonQueryResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.InputConfiguration)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.InputConfiguration())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.InputSubject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.InputSubject())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.InputType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.InputType())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.MessageConfiguration)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.MessageConfiguration())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.MessageLayout)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.MessageLayout())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.MessageStructure)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(PorticoService.MessageStructure()))>  _
        Function NewExecuteSQLNonQuery(ByVal QueryString As String) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/NewExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IPortico/NewExecuteSQLNonQueryResponse")>  _
        Function NewExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertInputConfiguration", ReplyAction:="http://tempuri.org/IPortico/InsertInputConfigurationResponse")>  _
        Sub InsertInputConfiguration(ByVal oInputConfiguration As PorticoService.InputConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertInputConfiguration", ReplyAction:="http://tempuri.org/IPortico/InsertInputConfigurationResponse")>  _
        Function InsertInputConfigurationAsync(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateInputConfiguration", ReplyAction:="http://tempuri.org/IPortico/UpdateInputConfigurationResponse")>  _
        Sub UpdateInputConfiguration(ByVal oInputConfiguration As PorticoService.InputConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateInputConfiguration", ReplyAction:="http://tempuri.org/IPortico/UpdateInputConfigurationResponse")>  _
        Function UpdateInputConfigurationAsync(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteInputConfiguration", ReplyAction:="http://tempuri.org/IPortico/DeleteInputConfigurationResponse")>  _
        Sub DeleteInputConfiguration(ByVal oInputConfiguration As PorticoService.InputConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteInputConfiguration", ReplyAction:="http://tempuri.org/IPortico/DeleteInputConfigurationResponse")>  _
        Function DeleteInputConfigurationAsync(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllInputConfiguration", ReplyAction:="http://tempuri.org/IPortico/GetAllInputConfigurationResponse")>  _
        Function GetAllInputConfiguration(ByVal oInputConfiguration As PorticoService.InputConfiguration) As PorticoService.InputConfiguration()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllInputConfiguration", ReplyAction:="http://tempuri.org/IPortico/GetAllInputConfigurationResponse")>  _
        Function GetAllInputConfigurationAsync(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Threading.Tasks.Task(Of PorticoService.InputConfiguration())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableInputConfiguration", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableInputConfigurationResponse")>  _
        Function GetAllDataTableInputConfiguration(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableInputConfiguration", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableInputConfigurationResponse")>  _
        Function GetAllDataTableInputConfigurationAsync(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertInputSubject", ReplyAction:="http://tempuri.org/IPortico/InsertInputSubjectResponse")>  _
        Sub InsertInputSubject(ByVal oInputSubject As PorticoService.InputSubject)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertInputSubject", ReplyAction:="http://tempuri.org/IPortico/InsertInputSubjectResponse")>  _
        Function InsertInputSubjectAsync(ByVal oInputSubject As PorticoService.InputSubject) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateInputSubject", ReplyAction:="http://tempuri.org/IPortico/UpdateInputSubjectResponse")>  _
        Sub UpdateInputSubject(ByVal oInputSubject As PorticoService.InputSubject)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateInputSubject", ReplyAction:="http://tempuri.org/IPortico/UpdateInputSubjectResponse")>  _
        Function UpdateInputSubjectAsync(ByVal oInputSubject As PorticoService.InputSubject) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteInputSubject", ReplyAction:="http://tempuri.org/IPortico/DeleteInputSubjectResponse")>  _
        Sub DeleteInputSubject(ByVal oInputSubject As PorticoService.InputSubject)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteInputSubject", ReplyAction:="http://tempuri.org/IPortico/DeleteInputSubjectResponse")>  _
        Function DeleteInputSubjectAsync(ByVal oInputSubject As PorticoService.InputSubject) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllInputSubject", ReplyAction:="http://tempuri.org/IPortico/GetAllInputSubjectResponse")>  _
        Function GetAllInputSubject(ByVal oInputSubject As PorticoService.InputSubject) As PorticoService.InputSubject()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllInputSubject", ReplyAction:="http://tempuri.org/IPortico/GetAllInputSubjectResponse")>  _
        Function GetAllInputSubjectAsync(ByVal oInputSubject As PorticoService.InputSubject) As System.Threading.Tasks.Task(Of PorticoService.InputSubject())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableInputSubject", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableInputSubjectResponse")>  _
        Function GetAllDataTableInputSubject(ByVal oInputSubject As PorticoService.InputSubject) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableInputSubject", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableInputSubjectResponse")>  _
        Function GetAllDataTableInputSubjectAsync(ByVal oInputSubject As PorticoService.InputSubject) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertInputType", ReplyAction:="http://tempuri.org/IPortico/InsertInputTypeResponse")>  _
        Sub InsertInputType(ByVal oInputType As PorticoService.InputType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertInputType", ReplyAction:="http://tempuri.org/IPortico/InsertInputTypeResponse")>  _
        Function InsertInputTypeAsync(ByVal oInputType As PorticoService.InputType) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateInputType", ReplyAction:="http://tempuri.org/IPortico/UpdateInputTypeResponse")>  _
        Sub UpdateInputType(ByVal oInputType As PorticoService.InputType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateInputType", ReplyAction:="http://tempuri.org/IPortico/UpdateInputTypeResponse")>  _
        Function UpdateInputTypeAsync(ByVal oInputType As PorticoService.InputType) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteInputType", ReplyAction:="http://tempuri.org/IPortico/DeleteInputTypeResponse")>  _
        Sub DeleteInputType(ByVal oInputType As PorticoService.InputType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteInputType", ReplyAction:="http://tempuri.org/IPortico/DeleteInputTypeResponse")>  _
        Function DeleteInputTypeAsync(ByVal oInputType As PorticoService.InputType) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllInputType", ReplyAction:="http://tempuri.org/IPortico/GetAllInputTypeResponse")>  _
        Function GetAllInputType(ByVal oInputType As PorticoService.InputType) As PorticoService.InputType()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllInputType", ReplyAction:="http://tempuri.org/IPortico/GetAllInputTypeResponse")>  _
        Function GetAllInputTypeAsync(ByVal oInputType As PorticoService.InputType) As System.Threading.Tasks.Task(Of PorticoService.InputType())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableInputType", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableInputTypeResponse")>  _
        Function GetAllDataTableInputType(ByVal oInputType As PorticoService.InputType) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableInputType", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableInputTypeResponse")>  _
        Function GetAllDataTableInputTypeAsync(ByVal oInputType As PorticoService.InputType) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertMessageConfiguration", ReplyAction:="http://tempuri.org/IPortico/InsertMessageConfigurationResponse")>  _
        Sub InsertMessageConfiguration(ByVal oMessageConfiguration As PorticoService.MessageConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertMessageConfiguration", ReplyAction:="http://tempuri.org/IPortico/InsertMessageConfigurationResponse")>  _
        Function InsertMessageConfigurationAsync(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateMessageConfiguration", ReplyAction:="http://tempuri.org/IPortico/UpdateMessageConfigurationResponse")>  _
        Sub UpdateMessageConfiguration(ByVal oMessageConfiguration As PorticoService.MessageConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateMessageConfiguration", ReplyAction:="http://tempuri.org/IPortico/UpdateMessageConfigurationResponse")>  _
        Function UpdateMessageConfigurationAsync(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteMessageConfiguration", ReplyAction:="http://tempuri.org/IPortico/DeleteMessageConfigurationResponse")>  _
        Sub DeleteMessageConfiguration(ByVal oMessageConfiguration As PorticoService.MessageConfiguration)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteMessageConfiguration", ReplyAction:="http://tempuri.org/IPortico/DeleteMessageConfigurationResponse")>  _
        Function DeleteMessageConfigurationAsync(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllMessageConfiguration", ReplyAction:="http://tempuri.org/IPortico/GetAllMessageConfigurationResponse")>  _
        Function GetAllMessageConfiguration(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As PorticoService.MessageConfiguration()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllMessageConfiguration", ReplyAction:="http://tempuri.org/IPortico/GetAllMessageConfigurationResponse")>  _
        Function GetAllMessageConfigurationAsync(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Threading.Tasks.Task(Of PorticoService.MessageConfiguration())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableMessageConfiguration", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableMessageConfigurationResponse")>  _
        Function GetAllDataTableMessageConfiguration(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableMessageConfiguration", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableMessageConfigurationResponse")>  _
        Function GetAllDataTableMessageConfigurationAsync(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertMessageLayout", ReplyAction:="http://tempuri.org/IPortico/InsertMessageLayoutResponse")>  _
        Sub InsertMessageLayout(ByVal oMessageLayout As PorticoService.MessageLayout)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertMessageLayout", ReplyAction:="http://tempuri.org/IPortico/InsertMessageLayoutResponse")>  _
        Function InsertMessageLayoutAsync(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateMessageLayout", ReplyAction:="http://tempuri.org/IPortico/UpdateMessageLayoutResponse")>  _
        Sub UpdateMessageLayout(ByVal oMessageLayout As PorticoService.MessageLayout)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateMessageLayout", ReplyAction:="http://tempuri.org/IPortico/UpdateMessageLayoutResponse")>  _
        Function UpdateMessageLayoutAsync(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteMessageLayout", ReplyAction:="http://tempuri.org/IPortico/DeleteMessageLayoutResponse")>  _
        Sub DeleteMessageLayout(ByVal oMessageLayout As PorticoService.MessageLayout)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteMessageLayout", ReplyAction:="http://tempuri.org/IPortico/DeleteMessageLayoutResponse")>  _
        Function DeleteMessageLayoutAsync(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllMessageLayout", ReplyAction:="http://tempuri.org/IPortico/GetAllMessageLayoutResponse")>  _
        Function GetAllMessageLayout(ByVal oMessageLayout As PorticoService.MessageLayout) As PorticoService.MessageLayout()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllMessageLayout", ReplyAction:="http://tempuri.org/IPortico/GetAllMessageLayoutResponse")>  _
        Function GetAllMessageLayoutAsync(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Threading.Tasks.Task(Of PorticoService.MessageLayout())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableMessageLayout", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableMessageLayoutResponse")>  _
        Function GetAllDataTableMessageLayout(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableMessageLayout", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableMessageLayoutResponse")>  _
        Function GetAllDataTableMessageLayoutAsync(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertMessageStructure", ReplyAction:="http://tempuri.org/IPortico/InsertMessageStructureResponse")>  _
        Sub InsertMessageStructure(ByVal oMessageStructure As PorticoService.MessageStructure)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/InsertMessageStructure", ReplyAction:="http://tempuri.org/IPortico/InsertMessageStructureResponse")>  _
        Function InsertMessageStructureAsync(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateMessageStructure", ReplyAction:="http://tempuri.org/IPortico/UpdateMessageStructureResponse")>  _
        Sub UpdateMessageStructure(ByVal oMessageStructure As PorticoService.MessageStructure)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/UpdateMessageStructure", ReplyAction:="http://tempuri.org/IPortico/UpdateMessageStructureResponse")>  _
        Function UpdateMessageStructureAsync(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteMessageStructure", ReplyAction:="http://tempuri.org/IPortico/DeleteMessageStructureResponse")>  _
        Sub DeleteMessageStructure(ByVal oMessageStructure As PorticoService.MessageStructure)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/DeleteMessageStructure", ReplyAction:="http://tempuri.org/IPortico/DeleteMessageStructureResponse")>  _
        Function DeleteMessageStructureAsync(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllMessageStructure", ReplyAction:="http://tempuri.org/IPortico/GetAllMessageStructureResponse")>  _
        Function GetAllMessageStructure(ByVal oMessageStructure As PorticoService.MessageStructure) As PorticoService.MessageStructure()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllMessageStructure", ReplyAction:="http://tempuri.org/IPortico/GetAllMessageStructureResponse")>  _
        Function GetAllMessageStructureAsync(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Threading.Tasks.Task(Of PorticoService.MessageStructure())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableMessageStructure", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableMessageStructureResponse")>  _
        Function GetAllDataTableMessageStructure(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPortico/GetAllDataTableMessageStructure", ReplyAction:="http://tempuri.org/IPortico/GetAllDataTableMessageStructureResponse")>  _
        Function GetAllDataTableMessageStructureAsync(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPorticoChannel
        Inherits PorticoService.IPortico, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PorticoClient
        Inherits System.ServiceModel.ClientBase(Of PorticoService.IPortico)
        Implements PorticoService.IPortico
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements PorticoService.IPortico.ExecuteSQL
            Return MyBase.Channel.ExecuteSQL(QueryString)
        End Function
        
        Public Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements PorticoService.IPortico.ExecuteSQLAsync
            Return MyBase.Channel.ExecuteSQLAsync(QueryString)
        End Function
        
        Public Function NewExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements PorticoService.IPortico.NewExecuteSQL
            Return MyBase.Channel.NewExecuteSQL(QueryString)
        End Function
        
        Public Function NewExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements PorticoService.IPortico.NewExecuteSQLAsync
            Return MyBase.Channel.NewExecuteSQLAsync(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQuery(ByVal QueryString As String) As Boolean Implements PorticoService.IPortico.ExecuteSQLNonQuery
            Return MyBase.Channel.ExecuteSQLNonQuery(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Boolean) Implements PorticoService.IPortico.ExecuteSQLNonQueryAsync
            Return MyBase.Channel.ExecuteSQLNonQueryAsync(QueryString)
        End Function
        
        Public Function NewExecuteSQLNonQuery(ByVal QueryString As String) As Object() Implements PorticoService.IPortico.NewExecuteSQLNonQuery
            Return MyBase.Channel.NewExecuteSQLNonQuery(QueryString)
        End Function
        
        Public Function NewExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object()) Implements PorticoService.IPortico.NewExecuteSQLNonQueryAsync
            Return MyBase.Channel.NewExecuteSQLNonQueryAsync(QueryString)
        End Function
        
        Public Sub InsertInputConfiguration(ByVal oInputConfiguration As PorticoService.InputConfiguration) Implements PorticoService.IPortico.InsertInputConfiguration
            MyBase.Channel.InsertInputConfiguration(oInputConfiguration)
        End Sub
        
        Public Function InsertInputConfigurationAsync(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Threading.Tasks.Task Implements PorticoService.IPortico.InsertInputConfigurationAsync
            Return MyBase.Channel.InsertInputConfigurationAsync(oInputConfiguration)
        End Function
        
        Public Sub UpdateInputConfiguration(ByVal oInputConfiguration As PorticoService.InputConfiguration) Implements PorticoService.IPortico.UpdateInputConfiguration
            MyBase.Channel.UpdateInputConfiguration(oInputConfiguration)
        End Sub
        
        Public Function UpdateInputConfigurationAsync(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Threading.Tasks.Task Implements PorticoService.IPortico.UpdateInputConfigurationAsync
            Return MyBase.Channel.UpdateInputConfigurationAsync(oInputConfiguration)
        End Function
        
        Public Sub DeleteInputConfiguration(ByVal oInputConfiguration As PorticoService.InputConfiguration) Implements PorticoService.IPortico.DeleteInputConfiguration
            MyBase.Channel.DeleteInputConfiguration(oInputConfiguration)
        End Sub
        
        Public Function DeleteInputConfigurationAsync(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Threading.Tasks.Task Implements PorticoService.IPortico.DeleteInputConfigurationAsync
            Return MyBase.Channel.DeleteInputConfigurationAsync(oInputConfiguration)
        End Function
        
        Public Function GetAllInputConfiguration(ByVal oInputConfiguration As PorticoService.InputConfiguration) As PorticoService.InputConfiguration() Implements PorticoService.IPortico.GetAllInputConfiguration
            Return MyBase.Channel.GetAllInputConfiguration(oInputConfiguration)
        End Function
        
        Public Function GetAllInputConfigurationAsync(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Threading.Tasks.Task(Of PorticoService.InputConfiguration()) Implements PorticoService.IPortico.GetAllInputConfigurationAsync
            Return MyBase.Channel.GetAllInputConfigurationAsync(oInputConfiguration)
        End Function
        
        Public Function GetAllDataTableInputConfiguration(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Data.DataTable Implements PorticoService.IPortico.GetAllDataTableInputConfiguration
            Return MyBase.Channel.GetAllDataTableInputConfiguration(oInputConfiguration)
        End Function
        
        Public Function GetAllDataTableInputConfigurationAsync(ByVal oInputConfiguration As PorticoService.InputConfiguration) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements PorticoService.IPortico.GetAllDataTableInputConfigurationAsync
            Return MyBase.Channel.GetAllDataTableInputConfigurationAsync(oInputConfiguration)
        End Function
        
        Public Sub InsertInputSubject(ByVal oInputSubject As PorticoService.InputSubject) Implements PorticoService.IPortico.InsertInputSubject
            MyBase.Channel.InsertInputSubject(oInputSubject)
        End Sub
        
        Public Function InsertInputSubjectAsync(ByVal oInputSubject As PorticoService.InputSubject) As System.Threading.Tasks.Task Implements PorticoService.IPortico.InsertInputSubjectAsync
            Return MyBase.Channel.InsertInputSubjectAsync(oInputSubject)
        End Function
        
        Public Sub UpdateInputSubject(ByVal oInputSubject As PorticoService.InputSubject) Implements PorticoService.IPortico.UpdateInputSubject
            MyBase.Channel.UpdateInputSubject(oInputSubject)
        End Sub
        
        Public Function UpdateInputSubjectAsync(ByVal oInputSubject As PorticoService.InputSubject) As System.Threading.Tasks.Task Implements PorticoService.IPortico.UpdateInputSubjectAsync
            Return MyBase.Channel.UpdateInputSubjectAsync(oInputSubject)
        End Function
        
        Public Sub DeleteInputSubject(ByVal oInputSubject As PorticoService.InputSubject) Implements PorticoService.IPortico.DeleteInputSubject
            MyBase.Channel.DeleteInputSubject(oInputSubject)
        End Sub
        
        Public Function DeleteInputSubjectAsync(ByVal oInputSubject As PorticoService.InputSubject) As System.Threading.Tasks.Task Implements PorticoService.IPortico.DeleteInputSubjectAsync
            Return MyBase.Channel.DeleteInputSubjectAsync(oInputSubject)
        End Function
        
        Public Function GetAllInputSubject(ByVal oInputSubject As PorticoService.InputSubject) As PorticoService.InputSubject() Implements PorticoService.IPortico.GetAllInputSubject
            Return MyBase.Channel.GetAllInputSubject(oInputSubject)
        End Function
        
        Public Function GetAllInputSubjectAsync(ByVal oInputSubject As PorticoService.InputSubject) As System.Threading.Tasks.Task(Of PorticoService.InputSubject()) Implements PorticoService.IPortico.GetAllInputSubjectAsync
            Return MyBase.Channel.GetAllInputSubjectAsync(oInputSubject)
        End Function
        
        Public Function GetAllDataTableInputSubject(ByVal oInputSubject As PorticoService.InputSubject) As System.Data.DataTable Implements PorticoService.IPortico.GetAllDataTableInputSubject
            Return MyBase.Channel.GetAllDataTableInputSubject(oInputSubject)
        End Function
        
        Public Function GetAllDataTableInputSubjectAsync(ByVal oInputSubject As PorticoService.InputSubject) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements PorticoService.IPortico.GetAllDataTableInputSubjectAsync
            Return MyBase.Channel.GetAllDataTableInputSubjectAsync(oInputSubject)
        End Function
        
        Public Sub InsertInputType(ByVal oInputType As PorticoService.InputType) Implements PorticoService.IPortico.InsertInputType
            MyBase.Channel.InsertInputType(oInputType)
        End Sub
        
        Public Function InsertInputTypeAsync(ByVal oInputType As PorticoService.InputType) As System.Threading.Tasks.Task Implements PorticoService.IPortico.InsertInputTypeAsync
            Return MyBase.Channel.InsertInputTypeAsync(oInputType)
        End Function
        
        Public Sub UpdateInputType(ByVal oInputType As PorticoService.InputType) Implements PorticoService.IPortico.UpdateInputType
            MyBase.Channel.UpdateInputType(oInputType)
        End Sub
        
        Public Function UpdateInputTypeAsync(ByVal oInputType As PorticoService.InputType) As System.Threading.Tasks.Task Implements PorticoService.IPortico.UpdateInputTypeAsync
            Return MyBase.Channel.UpdateInputTypeAsync(oInputType)
        End Function
        
        Public Sub DeleteInputType(ByVal oInputType As PorticoService.InputType) Implements PorticoService.IPortico.DeleteInputType
            MyBase.Channel.DeleteInputType(oInputType)
        End Sub
        
        Public Function DeleteInputTypeAsync(ByVal oInputType As PorticoService.InputType) As System.Threading.Tasks.Task Implements PorticoService.IPortico.DeleteInputTypeAsync
            Return MyBase.Channel.DeleteInputTypeAsync(oInputType)
        End Function
        
        Public Function GetAllInputType(ByVal oInputType As PorticoService.InputType) As PorticoService.InputType() Implements PorticoService.IPortico.GetAllInputType
            Return MyBase.Channel.GetAllInputType(oInputType)
        End Function
        
        Public Function GetAllInputTypeAsync(ByVal oInputType As PorticoService.InputType) As System.Threading.Tasks.Task(Of PorticoService.InputType()) Implements PorticoService.IPortico.GetAllInputTypeAsync
            Return MyBase.Channel.GetAllInputTypeAsync(oInputType)
        End Function
        
        Public Function GetAllDataTableInputType(ByVal oInputType As PorticoService.InputType) As System.Data.DataTable Implements PorticoService.IPortico.GetAllDataTableInputType
            Return MyBase.Channel.GetAllDataTableInputType(oInputType)
        End Function
        
        Public Function GetAllDataTableInputTypeAsync(ByVal oInputType As PorticoService.InputType) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements PorticoService.IPortico.GetAllDataTableInputTypeAsync
            Return MyBase.Channel.GetAllDataTableInputTypeAsync(oInputType)
        End Function
        
        Public Sub InsertMessageConfiguration(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) Implements PorticoService.IPortico.InsertMessageConfiguration
            MyBase.Channel.InsertMessageConfiguration(oMessageConfiguration)
        End Sub
        
        Public Function InsertMessageConfigurationAsync(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Threading.Tasks.Task Implements PorticoService.IPortico.InsertMessageConfigurationAsync
            Return MyBase.Channel.InsertMessageConfigurationAsync(oMessageConfiguration)
        End Function
        
        Public Sub UpdateMessageConfiguration(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) Implements PorticoService.IPortico.UpdateMessageConfiguration
            MyBase.Channel.UpdateMessageConfiguration(oMessageConfiguration)
        End Sub
        
        Public Function UpdateMessageConfigurationAsync(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Threading.Tasks.Task Implements PorticoService.IPortico.UpdateMessageConfigurationAsync
            Return MyBase.Channel.UpdateMessageConfigurationAsync(oMessageConfiguration)
        End Function
        
        Public Sub DeleteMessageConfiguration(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) Implements PorticoService.IPortico.DeleteMessageConfiguration
            MyBase.Channel.DeleteMessageConfiguration(oMessageConfiguration)
        End Sub
        
        Public Function DeleteMessageConfigurationAsync(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Threading.Tasks.Task Implements PorticoService.IPortico.DeleteMessageConfigurationAsync
            Return MyBase.Channel.DeleteMessageConfigurationAsync(oMessageConfiguration)
        End Function
        
        Public Function GetAllMessageConfiguration(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As PorticoService.MessageConfiguration() Implements PorticoService.IPortico.GetAllMessageConfiguration
            Return MyBase.Channel.GetAllMessageConfiguration(oMessageConfiguration)
        End Function
        
        Public Function GetAllMessageConfigurationAsync(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Threading.Tasks.Task(Of PorticoService.MessageConfiguration()) Implements PorticoService.IPortico.GetAllMessageConfigurationAsync
            Return MyBase.Channel.GetAllMessageConfigurationAsync(oMessageConfiguration)
        End Function
        
        Public Function GetAllDataTableMessageConfiguration(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Data.DataTable Implements PorticoService.IPortico.GetAllDataTableMessageConfiguration
            Return MyBase.Channel.GetAllDataTableMessageConfiguration(oMessageConfiguration)
        End Function
        
        Public Function GetAllDataTableMessageConfigurationAsync(ByVal oMessageConfiguration As PorticoService.MessageConfiguration) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements PorticoService.IPortico.GetAllDataTableMessageConfigurationAsync
            Return MyBase.Channel.GetAllDataTableMessageConfigurationAsync(oMessageConfiguration)
        End Function
        
        Public Sub InsertMessageLayout(ByVal oMessageLayout As PorticoService.MessageLayout) Implements PorticoService.IPortico.InsertMessageLayout
            MyBase.Channel.InsertMessageLayout(oMessageLayout)
        End Sub
        
        Public Function InsertMessageLayoutAsync(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Threading.Tasks.Task Implements PorticoService.IPortico.InsertMessageLayoutAsync
            Return MyBase.Channel.InsertMessageLayoutAsync(oMessageLayout)
        End Function
        
        Public Sub UpdateMessageLayout(ByVal oMessageLayout As PorticoService.MessageLayout) Implements PorticoService.IPortico.UpdateMessageLayout
            MyBase.Channel.UpdateMessageLayout(oMessageLayout)
        End Sub
        
        Public Function UpdateMessageLayoutAsync(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Threading.Tasks.Task Implements PorticoService.IPortico.UpdateMessageLayoutAsync
            Return MyBase.Channel.UpdateMessageLayoutAsync(oMessageLayout)
        End Function
        
        Public Sub DeleteMessageLayout(ByVal oMessageLayout As PorticoService.MessageLayout) Implements PorticoService.IPortico.DeleteMessageLayout
            MyBase.Channel.DeleteMessageLayout(oMessageLayout)
        End Sub
        
        Public Function DeleteMessageLayoutAsync(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Threading.Tasks.Task Implements PorticoService.IPortico.DeleteMessageLayoutAsync
            Return MyBase.Channel.DeleteMessageLayoutAsync(oMessageLayout)
        End Function
        
        Public Function GetAllMessageLayout(ByVal oMessageLayout As PorticoService.MessageLayout) As PorticoService.MessageLayout() Implements PorticoService.IPortico.GetAllMessageLayout
            Return MyBase.Channel.GetAllMessageLayout(oMessageLayout)
        End Function
        
        Public Function GetAllMessageLayoutAsync(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Threading.Tasks.Task(Of PorticoService.MessageLayout()) Implements PorticoService.IPortico.GetAllMessageLayoutAsync
            Return MyBase.Channel.GetAllMessageLayoutAsync(oMessageLayout)
        End Function
        
        Public Function GetAllDataTableMessageLayout(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Data.DataTable Implements PorticoService.IPortico.GetAllDataTableMessageLayout
            Return MyBase.Channel.GetAllDataTableMessageLayout(oMessageLayout)
        End Function
        
        Public Function GetAllDataTableMessageLayoutAsync(ByVal oMessageLayout As PorticoService.MessageLayout) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements PorticoService.IPortico.GetAllDataTableMessageLayoutAsync
            Return MyBase.Channel.GetAllDataTableMessageLayoutAsync(oMessageLayout)
        End Function
        
        Public Sub InsertMessageStructure(ByVal oMessageStructure As PorticoService.MessageStructure) Implements PorticoService.IPortico.InsertMessageStructure
            MyBase.Channel.InsertMessageStructure(oMessageStructure)
        End Sub
        
        Public Function InsertMessageStructureAsync(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Threading.Tasks.Task Implements PorticoService.IPortico.InsertMessageStructureAsync
            Return MyBase.Channel.InsertMessageStructureAsync(oMessageStructure)
        End Function
        
        Public Sub UpdateMessageStructure(ByVal oMessageStructure As PorticoService.MessageStructure) Implements PorticoService.IPortico.UpdateMessageStructure
            MyBase.Channel.UpdateMessageStructure(oMessageStructure)
        End Sub
        
        Public Function UpdateMessageStructureAsync(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Threading.Tasks.Task Implements PorticoService.IPortico.UpdateMessageStructureAsync
            Return MyBase.Channel.UpdateMessageStructureAsync(oMessageStructure)
        End Function
        
        Public Sub DeleteMessageStructure(ByVal oMessageStructure As PorticoService.MessageStructure) Implements PorticoService.IPortico.DeleteMessageStructure
            MyBase.Channel.DeleteMessageStructure(oMessageStructure)
        End Sub
        
        Public Function DeleteMessageStructureAsync(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Threading.Tasks.Task Implements PorticoService.IPortico.DeleteMessageStructureAsync
            Return MyBase.Channel.DeleteMessageStructureAsync(oMessageStructure)
        End Function
        
        Public Function GetAllMessageStructure(ByVal oMessageStructure As PorticoService.MessageStructure) As PorticoService.MessageStructure() Implements PorticoService.IPortico.GetAllMessageStructure
            Return MyBase.Channel.GetAllMessageStructure(oMessageStructure)
        End Function
        
        Public Function GetAllMessageStructureAsync(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Threading.Tasks.Task(Of PorticoService.MessageStructure()) Implements PorticoService.IPortico.GetAllMessageStructureAsync
            Return MyBase.Channel.GetAllMessageStructureAsync(oMessageStructure)
        End Function
        
        Public Function GetAllDataTableMessageStructure(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Data.DataTable Implements PorticoService.IPortico.GetAllDataTableMessageStructure
            Return MyBase.Channel.GetAllDataTableMessageStructure(oMessageStructure)
        End Function
        
        Public Function GetAllDataTableMessageStructureAsync(ByVal oMessageStructure As PorticoService.MessageStructure) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements PorticoService.IPortico.GetAllDataTableMessageStructureAsync
            Return MyBase.Channel.GetAllDataTableMessageStructureAsync(oMessageStructure)
        End Function
    End Class
End Namespace
